export const industry010801 = [
{
    question: "CAN(Controller Area Network) 통신에서 메시지의 우선순위를 결정하는 필드는 무엇이며, 그 결정 방식은?",
    options: ["Data Field, 길이가 짧을수록 높다", "DLC (Data Length Code), 값이 클수록 높다", "Arbitration Field, 값이 낮을수록 높다", "CRC Field, 값이 높을수록 높다"],
    answer: 2,
    explain: "CAN의 Arbitration Field(중재 필드)는 Identifier(ID)를 포함하며, ID 값이 낮을수록 우선순위가 높고 버스 제어권을 갖는다. 이를 Non-Destructive Arbitration이라고 한다.",
  },
  {
    question: "고속 CAN(High-Speed CAN) 통신에서 CAN-H와 CAN-L 두 신호선에 120Ω의 종단 저항(Termination Resistor)을 사용하는 주된 이유는?",
    options: ["데이터 전송 속도 제한", "버스에 흐르는 전류 증가", "신호 반사에 의한 파형 왜곡 방지", "버스 전원 공급"],
    answer: 2,
    explain: "종단 저항은 통신선의 임피던스 정합을 통해 신호가 통신선 끝에서 반사되어 원래 신호와 겹쳐 파형을 왜곡하는 현상을 방지한다.",
  },
  {
    question: "CAN 통신의 표준 프레임(Standard Frame)에서 메시지 식별자(Identifier)의 비트 수와 최대 데이터 필드 길이(바이트)는?",
    options: ["11비트, 8바이트", "29비트, 8바이트", "11비트, 64바이트", "29비트, 64바이트"],
    answer: 0,
    explain: "표준 CAN 프레임의 식별자는 11비트이며, 데이터 필드(Data Field)는 최대 8바이트까지 전송할 수 있다.",
  },
  {
    question: "CAN 통신에서 연속적으로 동일한 레벨(Dominant 또는 Recessive)의 비트가 전송될 때, 오류를 방지하고 동기화를 유지하기 위해 삽입되는 비트는?",
    options: ["Parity Bit", "Stop Bit", "Stuff Bit", "ACK Bit"],
    answer: 2,
    explain: "Bit Stuffing은 연속되는 5개의 동일 레벨 비트 뒤에 강제로 반대 레벨의 비트를 삽입하여 동기화 오류를 막고 전송 중 오류 검출에 활용된다.",
  },
  {
    question: "LIN(Local Interconnect Network) 프로토콜의 주된 특징으로 옳지 않은 것은?",
    options: ["단일 마스터와 다수의 슬레이브 구조", "시계열(Time-triggered) 통신 방식", "저속 통신과 저비용에 초점", "단일선(Single-wire) 통신 방식"],
    answer: 1,
    explain: "LIN은 마스터의 스케줄링 테이블에 의해 제어되는 이벤트 기반 통신 방식이며, 시계열(Time-triggered) 통신은 FlexRay의 주된 특징이다.",
  },
  {
    question: "고속 CAN 통신 시, CAN-H 라인이 단선(Open)되어 접지(Ground)에 단락(Short to Ground)되었을 때, 버스 상태에 미치는 영향은?",
    options: ["통신 속도가 절반으로 줄어든다.", "CAN-L 라인이 통신을 이어받아 정상 통신한다.", "버스 전체가 Dominant 상태로 고정되어 통신 불능 상태가 된다.", "버스 전체가 Recessive 상태로 고정되어 통신 불능 상태가 된다."],
    answer: 2,
    explain: "CAN-H가 접지 단락되면 CAN-H의 전위가 낮아지고, CAN-L과의 차동 전압이 Dominant 상태를 유지하게 되어 버스가 Dominant 고정으로 통신 불능이 된다.",
  },
  {
    question: "자동차 네트워크에서 서로 다른 통신 프로토콜(예: CAN, LIN, FlexRay)을 사용하는 ECU 간에 데이터를 중계하고 변환하는 장치는?",
    options: ["Transceiver", "Termination Resistor", "Gateway ECU", "Bus Driver"],
    answer: 2,
    explain: "Gateway ECU(게이트웨이 ECU)는 서로 다른 네트워크 간의 데이터 포맷을 변환하고 라우팅하여 통신을 가능하게 한다.",
  },
  {
    question: "CAN 통신 프레임의 ACK 필드(Acknowledge Field)에서 송신 ECU는 어떤 상태의 비트를 전송하는가?",
    options: ["Dominant 비트를 전송한다.", "Recessive 비트를 전송한다.", "ACK 필드를 사용하지 않는다.", "이전 비트의 반대 레벨을 전송한다."],
    answer: 1,
    explain: "송신 ECU는 Recessive 비트를 전송하며, 수신에 성공한 모든 ECU는 이 비트를 Dominant로 덮어써서 성공적인 수신을 송신 ECU에 알린다.",
  },
  {
    question: "FlexRay 통신 프로토콜이 CAN이나 LIN과 비교하여 갖는 가장 큰 장점은?",
    options: ["초저가 구현 비용", "마스터/슬레이브의 단순한 제어 구조", "실시간성과 높은 신뢰성을 보장하는 시계열(Time-triggered) 통신", "단일선(Single-wire) 통신"],
    answer: 2,
    explain: "FlexRay는 Time-Triggered 통신 방식을 도입하여 엄격한 시간 동기화를 통해 데이터 전송의 실시간성과 예측 가능성을 극대화한다.",
  },
  {
    question: "CAN 통신에서 Recessive 비트 상태 시, CAN-H와 CAN-L의 공칭(Nominal) 전압 레벨은?",
    options: ["CAN-H: 5V, CAN-L: 0V", "CAN-H: 3.5V, CAN-L: 1.5V", "CAN-H: 2.5V, CAN-L: 2.5V", "CAN-H: 0V, CAN-L: 5V"],
    answer: 2,
    explain: "Recessive 상태는 버스 휴지 상태로, CAN-H와 CAN-L 모두 공통 모드 전압인 약 2.5V를 유지하여 차동 전압이 0V에 가깝다.",
  },
  {
    question: "CAN 통신 프로토콜에서 수신된 메시지에 오류가 있음을 감지했을 때, 오류를 감지한 수신 ECU가 전송하는 오류 신호는?",
    options: ["Overload Frame", "Error Flag", "Stuff Bit", "ACK Bit"],
    answer: 1,
    explain: "오류가 감지된 ECU는 Error Flag(오류 플래그)를 버스에 전송하여 현재 메시지의 전송을 강제로 중단하고 오류 상태를 알린다.",
  },
  {
    question: "LIN 통신 프레임에서 마스터 노드가 슬레이브 노드에 데이터 전송을 요청하는 필드는?",
    options: ["Data Field", "CRC Field", "ID Field (식별자)", "Sync Field"],
    answer: 2,
    explain: "LIN은 마스터가 식별자(ID)를 포함한 헤더(Header)를 전송하면, 해당 ID에 응답하는 슬레이브가 데이터와 체크섬을 전송하는 방식으로 통신한다.",
  },
  {
    question: "CAN 통신에서 메시지 전송 후, 수신 ECU가 ACK 필드를 Dominant로 변경하지 않았을 때(ACK 에러), 송신 ECU가 취하는 조치는?",
    options: ["메시지 전송을 중단하고 Bus-Off 상태로 진입", "다음 메시지를 전송", "오류 카운터를 증가시키고 메시지를 재전송", "통신 속도를 낮춘다."],
    answer: 2,
    explain: "ACK 에러는 메시지가 정상적으로 수신되지 않았음을 의미하며, 송신 ECU는 오류 카운터를 증가시키고 해당 메시지를 재전송한다.",
  },
  {
    question: "CAN 통신 프레임에서 데이터 필드(Data Field)에 전송할 데이터가 전혀 없을 때, DLC (Data Length Code)의 값은?",
    options: ["0", "1", "8", "15"],
    answer: 0,
    explain: "DLC는 데이터 필드의 실제 길이를 나타내며, 데이터가 없을 경우 0으로 설정된다. 이 경우 'Remote Frame(원격 프레임)'과 구별된다.",
  },
  {
    question: "자동차 ECU 간의 통신에서 CAN 통신이 주로 사용되는 영역으로 가장 적합한 것은?",
    options: ["멀티미디어 및 인포테인먼트 시스템", "도어 잠금 장치 및 라이트 제어(저속)", "파워트레인 및 샤시 제어(고속)", "타이어 공기압 센서 통신"],
    answer: 2,
    explain: "CAN은 높은 신뢰성과 적절한 통신 속도(최대 1Mbps)를 제공하여 파워트레인, 샤시 제어 등 안전과 관련된 핵심 영역에 주로 사용된다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 담당하는 가장 중요한 기능은?",
    options: ["데이터 오류 자동 정정", "버스 종단 저항 설치", "통신 스케줄링 및 동기화", "다중 마스터 제어"],
    answer: 2,
    explain: "LIN은 마스터 노드가 전송 헤더를 주기적으로 전송하여 버스상의 모든 통신을 스케줄링하고 슬레이브 노드의 동기화를 유지한다.",
  },
  {
    question: "FlexRay 통신에서 높은 신뢰성을 확보하기 위해 사용하는 방법 중 하나로, 두 개의 채널(Channel A, Channel B)을 이용하여 동일 데이터를 전송하는 방식은?",
    options: ["Single-Channel Mode", "Dual-Mode Redundancy", "Time-Triggered Slot", "Dynamic Segment"],
    answer: 1,
    explain: "Dual-Mode Redundancy는 두 개의 독립된 채널을 통해 동일한 데이터를 전송하여 하나의 채널에 오류가 발생하더라도 통신을 유지할 수 있게 한다.",
  },
  {
    question: "CAN 통신에서 Dominant 비트 상태 시, CAN-H와 CAN-L의 공칭(Nominal) 전압 레벨은?",
    options: ["CAN-H: 5V, CAN-L: 0V", "CAN-H: 3.5V, CAN-L: 1.5V", "CAN-H: 2.5V, CAN-L: 2.5V", "CAN-H: 1.5V, CAN-L: 3.5V"],
    answer: 1,
    explain: "Dominant 상태는 버스에서 데이터가 전송되는 상태로, CAN-H는 약 3.5V, CAN-L은 약 1.5V를 유지하여 차동 전압이 2V가 된다.",
  },
  {
    question: "CAN 통신에서 ECU가 오류 카운터를 누적하여 Bus-Off 상태로 진입하는 기준은?",
    options: ["전송 오류 카운터가 127을 초과할 때", "수신 오류 카운터가 127을 초과할 때", "전송 오류 카운터가 255를 초과할 때", "전송 오류 카운터가 255를 초과하고 수신 오류 카운터가 127을 초과할 때"],
    answer: 2,
    explain: "CAN 프로토콜은 전송 오류 카운터가 255를 초과하면 해당 ECU를 Bus-Off 상태로 전환하여 버스에서 격리시킨다.",
  },
  {
    question: "CAN 프레임에서 비트 레벨의 위반(예: Stuff Bit 규칙 위반, 프레임 구조의 고정 필드 비트 위반 등)이 감지되었을 때 발생하는 오류 유형은?",
    options: ["Bit Error", "Form Error", "CRC Error", "ACK Error"],
    answer: 1,
    explain: "Form Error(형식 오류)는 CAN 프레임의 고정된 형식(예: Start of Frame, ACK Delimiter 등)이나 Bit Stuffing 규칙 위반 시 발생한다.",
  },
  {
    question: "OBD-II 진단 커넥터(DLC)의 핀 배열 중, CAN 통신에 사용되는 핀 번호는?",
    options: ["핀 7 (K-Line) 및 핀 15 (L-Line)", "핀 4 (섀시 접지) 및 핀 5 (신호 접지)", "핀 6 (CAN-H) 및 핀 14 (CAN-L)", "핀 2 (J1850 PWM) 및 핀 10 (J1850 VPW)"],
    answer: 2,
    explain: "OBD-II 규격에 따라 CAN 통신은 핀 6(CAN-H)과 핀 14(CAN-L)을 통해 이루어지며, 이는 범용적으로 사용된다.",
  },
  {
    question: "CAN 통신에서 CRC 필드(Cyclic Redundancy Check)의 주된 목적은?",
    options: ["메시지의 우선순위 결정", "수신 ECU의 정상 수신 확인", "전송된 데이터의 오류 검출", "통신 속도 조절"],
    answer: 2,
    explain: "CRC 필드는 전송된 데이터에 기반한 다항식 계산 결과를 포함하여, 수신 측에서 동일 계산 후 비교를 통해 데이터의 오류 발생 여부를 검출한다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 데이터를 전송하는 시점은?",
    options: ["마스터 노드가 버스가 비었음을 알릴 때", "슬레이브 노드 스스로 데이터 전송이 필요할 때", "마스터 노드가 해당 슬레이브의 ID를 포함한 헤더를 전송했을 때", "Sync Break 신호가 감지되었을 때"],
    answer: 2,
    explain: "LIN은 마스터가 스케줄에 따라 ID를 포함한 헤더를 전송하면, 해당 ID에 응답하는 슬레이브 노드가 데이터와 체크섬을 이어서 전송한다.",
  },
  {
    question: "MDPS(전동식 파워 스티어링) 제어 시스템과 같은 안전 핵심 기능에 CAN 대신 FlexRay 통신을 사용하는 주된 기술적 이유는?",
    options: ["FlexRay의 저비용 구현", "FlexRay의 시간 동기화 및 결정론적(Deterministic) 통신 특성", "FlexRay의 단일선 통신 방식", "FlexRay의 단순한 프레임 구조"],
    answer: 1,
    explain: "FlexRay는 시간 동기화 기반으로 데이터 전송이 정해진 시간 내에 이루어짐(결정론적)을 보장하여 높은 수준의 안정성과 실시간성이 요구되는 시스템에 적합하다.",
  },
  {
    question: "CAN 통신에서 CAN-H 또는 CAN-L 중 한 선만 단선(Open)되었을 때, 고속 CAN 통신에 미치는 영향은?",
    options: ["통신이 완전히 중단된다.", "버스 전체가 Dominant 상태로 고정된다.", "차동 신호 대신 단일 종단(Single-ended) 신호로 통신 속도가 저하되거나 오류 발생", "CAN-L이 전압 레벨을 2배로 높여 통신을 이어간다."],
    answer: 2,
    explain: "고속 CAN은 차동 신호에 의존하지만, 한 선 단선 시 일시적으로 단일 종단 신호처럼 작동하려 시도하나, 외부 노이즈에 취약해져 통신 오류가 발생하거나 중단된다.",
  },
  {
    question: "CAN 통신에서 ECU가 버스에 메시지를 전송할 때, Dominant 비트가 Recessive 비트보다 우선순위가 높은(버스를 이기는) 이유는?",
    options: ["Dominant는 5V, Recessive는 0V이기 때문", "Dominant 상태는 모든 ECU가 동시에 구동 가능하며, Recessive는 그렇지 않기 때문", "Dominant는 논리값 '0'을, Recessive는 논리값 '1'을 나타내기 때문", "Dominant 비트의 전송 시간이 더 짧기 때문"],
    answer: 2,
    explain: "Dominant(논리 0)는 버스 전압을 강하게 낮추어 다른 Recessive(논리 1) 신호를 덮어쓸 수 있으며, 두 메시지가 충돌 시 ID가 낮은(0이 많은) 메시지가 최종적으로 버스 제어권을 갖는다.",
  },
  {
    question: "FlexRay 통신에서 'Static Segment(정적 세그먼트)'의 주된 특징은?",
    options: ["충돌 방지를 위한 메시지 우선순위 중재", "전송 시간이 고정되어 높은 예측 가능성을 보장", "데이터 전송량이 유동적이며 유연함", "다수의 마스터 노드 지원"],
    answer: 1,
    explain: "Static Segment는 Time Slot이 미리 할당되어 정해진 시간(시계열)에만 메시지를 전송하므로, 통신 전송 시간에 대한 높은 예측 가능성을 갖는다.",
  },
  {
    question: "CAN 통신에서 오류를 감지한 ECU가 Error Flag를 전송한 후, 모든 ECU가 이어서 전송하는 필드는?",
    options: ["Overload Flag", "Error Delimiter", "ACK Field", "DLC Field"],
    answer: 1,
    explain: "Error Flag 전송 후, ECU들은 Error Delimiter(오류 한정자)를 전송하여 오류 상태를 명확히 구분하고 다음 메시지 전송을 준비한다.",
  },
  {
    question: "LIN 통신에서 Sync Break 필드가 헤더의 가장 앞에 위치하는 주된 목적은?",
    options: ["데이터 오류 검출", "슬레이브 노드의 물리적인 동기화", "메시지 우선순위 결정", "마스터 노드의 데이터 전송"],
    answer: 1,
    explain: "Sync Break는 일반적인 통신 비트 폭보다 긴 길이로, 슬레이브 노드가 통신 시작을 인지하고 비트 타이밍을 마스터와 동기화하는 데 사용된다.",
  },
  {
    question: "CAN 통신의 확장 프레임(Extended Frame)에서 메시지 식별자(Identifier)의 총 비트 수는?",
    options: ["11비트", "18비트", "29비트", "64비트"],
    answer: 2,
    explain: "확장 CAN 프레임은 표준 11비트에 18비트 확장 식별자를 추가하여 총 29비트의 식별자를 사용한다.",
  },
  {
    question: "자동차 네트워크에서 멀티미디어 및 인포테인먼트 시스템에 주로 사용되며, 광섬유를 이용한 고속 통신을 특징으로 하는 프로토콜은?",
    options: ["LIN", "CAN", "MOST (Media Oriented Systems Transport)", "FlexRay"],
    answer: 2,
    explain: "MOST는 높은 대역폭이 필요한 오디오, 비디오, 내비게이션 등 멀티미디어 데이터 전송을 위해 개발되었으며, 주로 광섬유를 사용한다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Error Passive(오류 수동)' 상태로 진입하는 기준은?",
    options: ["전송 오류 카운터가 127을 초과할 때", "전송 오류 카운터가 255를 초과할 때", "전송 또는 수신 오류 카운터가 127을 초과할 때", "오류 카운터가 0일 때"],
    answer: 2,
    explain: "전송 오류 카운터 또는 수신 오류 카운터 중 하나라도 127을 초과하면 ECU는 Error Passive 상태로 진입한다.",
  },
  {
    question: "CAN 통신에서 CRC 에러(순환 중복 검사 오류)가 발생했다면, 이는 주로 어느 필드에서 발생한 오류를 의미하는가?",
    options: ["Arbitration Field", "ACK Field", "Data Field 또는 CRC Field 자체", "Start of Frame Field"],
    answer: 2,
    explain: "CRC 에러는 Data Field와 CRC Field 자체를 포함한 전송 데이터에 오류가 발생하여 수신 측에서 계산한 값과 수신한 CRC 값이 일치하지 않을 때 발생한다.",
  },
  {
    question: "CAN 트랜시버(Transceiver)의 주된 역할은?",
    options: ["메시지 우선순위 결정", "데이터 오류 검출 및 정정", "ECU의 디지털 신호를 버스의 물리적 차동 신호로 변환", "버스 전원 공급"],
    answer: 2,
    explain: "트랜시버는 ECU의 CAN 컨트롤러가 생성하는 디지털 신호(TXD/RXD)를 CAN 버스상의 물리적인 차동 신호(CAN-H/CAN-L)로 변환하는 역할을 한다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment(동적 세그먼트)'의 주된 특징은?",
    options: ["전송 시간이 고정되어 예측 가능성이 높음", "데이터 전송량이 유동적이며 유연함", "버스에 충돌 발생 시 우선순위 중재", "단일 채널 통신"],
    answer: 1,
    explain: "Dynamic Segment는 시간 할당이 유동적이며, 메시지 전송이 필요할 때만 대역폭을 할당하여 데이터 전송의 유연성을 확보한다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 자신의 응답을 시작할 수 있도록 허용된 최대 지연 시간(슬립 모드 진입 전)은?",
    options: ["Sync Break 후 1ms", "헤더 수신 후 10ms", "마스터 노드가 지정하는 시간", "슬레이브 노드 스스로 결정"],
    answer: 2,
    explain: "LIN은 마스터가 스케줄링하므로, 슬레이브는 마스터가 정의한 스케줄에 따라 정해진 지연 시간 내에 응답을 시작해야 한다.",
  },
  {
    question: "CAN 통신에서 Bit Stuffing 규칙 위반(연속 6개 동일 레벨 비트 발생)이 감지되었을 때 발생하는 오류 유형은?",
    options: ["Bit Error", "Stuff Error", "Form Error", "CRC Error"],
    answer: 1,
    explain: "Stuff Error(스터프 오류)는 Bit Stuffing 규칙에 따라 삽입되어야 할 비트가 없거나, 연속 5개 이상의 동일 비트 레벨이 발생하는 경우에 검출된다.",
  },
  {
    question: "자동차 ECU 간의 통신에서 LIN 통신이 주로 사용되는 영역으로 가장 적합한 것은?",
    options: ["파워트레인 및 샤시 제어", "안전 제어 시스템(ABS, ESC)", "도어 잠금 장치, 창문 제어, 미러 등 저속 편의 장치 제어", "차량 진단 및 플래시 프로그래밍"],
    answer: 2,
    explain: "LIN은 저속, 저비용 구현이 가능하여 도어 모듈, 에어컨 제어, 라이트 스위치 등 비핵심 편의 장치 제어에 주로 사용된다.",
  },
  {
    question: "CAN 통신에서 CAN-H와 CAN-L의 공통 모드 전압(Common Mode Voltage)이 변하는 주된 원인은?",
    options: ["메시지 우선순위 중재", "버스 오류 발생", "ECU의 전원 전압 변화 또는 외부 노이즈 유입", "종단 저항 값의 변화"],
    answer: 2,
    explain: "공통 모드 전압은 외부의 전기적 간섭이나 ECU 전원의 변동에 의해 함께 변동할 수 있다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Error Passive' 상태로 진입했을 때, 버스에 오류를 알리기 위해 전송하는 Error Flag의 길이는?",
    options: ["6 Dominant 비트", "6 Recessive 비트", "8 Recessive 비트", "8 Dominant 비트"],
    answer: 2,
    explain: "Error Passive 상태의 ECU는 'Passive Error Flag'인 8개의 Recessive 비트를 전송하여, 다른 ECU의 통신에 미치는 영향을 최소화한다.",
  }  
];

export const industry010802 = [
{
    question: "CAN 통신에서 ECU가 'Error Passive' 상태로 진입했을 때, 해당 ECU가 메시지 충돌(Arbitration)에 참여하는 방식은?",
    options: ["Bus-Off 상태로 즉시 진입하여 참여 중단", "Recessive 비트만 전송하여 다른 ECU의 Dominant 비트에 영향을 주지 않음", "Dominant 비트만 전송하여 우선권을 확보", "정상적인 ECU와 동일하게 참여"],
    answer: 1,
    explain: "Error Passive 상태의 ECU는 다른 ECU의 통신에 미치는 영향을 최소화하기 위해 오류 감지 시 Passive Error Flag(Recessive 8비트)를 전송한다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-L 라인이 단선(Open)되어 전원(VCC, 5V)에 단락(Short to VCC)되었을 때, 버스 상태에 미치는 영향은?",
    options: ["버스 전체가 Recessive 상태로 고정되어 통신 불능 상태가 된다.", "CAN-H 라인이 통신을 이어받아 정상 통신한다.", "버스 전체가 Dominant 상태로 고정되어 통신 불능 상태가 된다.", "통신 속도가 절반으로 줄어든다."],
    answer: 2,
    explain: "CAN-L이 VCC에 단락되면 CAN-L의 전위가 높아지고, CAN-H와의 차동 전압이 Dominant 상태를 유지하게 되어 버스가 Dominant 고정으로 통신 불능이 된다.",
  },
  {
    question: "LIN 통신 프레임에서 헤더(Header)의 Sync Field(동기 필드)를 전송하는 주체와 그 주된 목적은?",
    options: ["슬레이브, 데이터 오류 검출", "슬레이브, 메시지 우선순위 결정", "마스터, 슬레이브의 클럭 동기화", "마스터, 데이터 전송 길이 지정"],
    answer: 2,
    explain: "Sync Field는 Sync Break 다음에 마스터가 전송하는 필드로, 슬레이브 노드가 내부 클럭을 마스터와 동기화하는 데 사용된다.",
  },
  {
    question: "CAN 통신에서 ECU가 Bus-Off 상태에서 Bus-On 상태로 복귀하기 위해 만족해야 하는 가장 중요한 조건은?",
    options: ["전송 오류 카운터를 0으로 초기화", "메시지 우선순위를 낮춘다.", "Recessive 비트를 128회 연속 감지", "CAN 버스를 5초간 모니터링"],
    answer: 2,
    explain: "Bus-Off 상태의 ECU는 버스가 128회 연속 Recessive 비트(버스 휴지 상태)임을 감지해야만 다시 Bus-On(Error Passive) 상태로 복귀할 수 있다.",
  },
  {
    question: "FlexRay 통신에서 'Cycle(사이클)'이 갖는 가장 중요한 의미는?",
    options: ["단일 메시지 전송 시간", "통신 속도", "Static Segment와 Dynamic Segment를 모두 포함하는 전체 통신 주기", "오류 발생 시 재전송 횟수"],
    answer: 2,
    explain: "FlexRay 사이클은 정적 세그먼트와 동적 세그먼트, 그리고 가드 시간 등을 포함하는 전체 반복 통신 주기를 의미하며, 시간 동기화의 기본 단위이다.",
  },
  {
    question: "자동차 진단 프로토콜인 UDS(Unified Diagnostic Services, ISO 14229)가 CAN 통신 기반에서 사용될 때, 이를 지칭하는 명칭은?",
    options: ["LIN UDS", "FlexRay UDS", "K-Line UDS", "DoCAN (Diagnostics over CAN)"],
    answer: 3,
    explain: "DoCAN은 CAN 통신 프로토콜을 기반으로 UDS 진단 서비스 메시지를 전송하는 방식이다.",
  },
  {
    question: "CAN 통신에서 두 개 이상의 ECU가 동시에 메시지 전송을 시작했을 때, 발생하는 현상은?",
    options: ["오류 발생으로 메시지가 즉시 중단된다.", "메시지 길이가 짧은 ECU가 우선권을 갖는다.", "ID 값이 낮은 ECU가 우선권을 획득하고 계속 전송한다.", "두 메시지가 동시에 버스에 전송된다."],
    answer: 2,
    explain: "CAN은 Dominant/Recessive 논리를 이용한 비파괴적 중재(Non-Destructive Arbitration)를 통해 ID 값이 낮은(우선순위가 높은) ECU가 버스 제어권을 갖는다.",
  },
  {
    question: "LIN 통신 프레임의 체크섬(Checksum) 필드가 보장하는 오류 제어 방식은?",
    options: ["데이터 오류 자동 정정", "메시지 우선순위 검증", "전송 데이터의 오류 검출", "슬레이브 노드의 응답 시간 검증"],
    answer: 2,
    explain: "LIN 체크섬은 데이터 필드를 포함한 특정 필드 값을 기반으로 계산되어 전송되며, 수신 측에서 동일 계산 후 비교하여 데이터의 오류 발생 여부를 검출한다.",
  },
  {
    question: "FlexRay 통신에서 동기화(Synchronization)의 기본이 되는 것은?",
    options: ["버스 전압 레벨", "메시지 ID", "전송된 타임 슬롯(Time Slot)", "데이터 필드 길이"],
    answer: 2,
    explain: "FlexRay는 시간 동기화 기반 통신으로, 모든 노드가 정해진 타임 슬롯(Time Slot)을 기준으로 엄격하게 통신 시간을 동기화한다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Error Active(오류 활성)' 상태일 때, 버스에 오류를 알리기 위해 전송하는 Error Flag의 길이는?",
    options: ["6 Dominant 비트", "6 Recessive 비트", "8 Recessive 비트", "8 Dominant 비트"],
    answer: 0,
    explain: "Error Active 상태의 ECU는 'Active Error Flag'인 6개의 Dominant 비트를 전송하여 모든 ECU가 오류를 인지하도록 강제한다.",
  },
  {
    question: "자동차 네트워크에서 서로 다른 CAN 버스(예: 파워트레인 CAN과 바디 CAN) 간의 통신을 중계하는 장치는?",
    options: ["Transceiver", "Termination Resistor", "Gateway ECU", "CAN Controller"],
    answer: 2,
    explain: "Gateway ECU(게이트웨이 ECU)는 서로 다른 네트워크 프로토콜이나 속도를 가진 CAN 버스 사이에서 데이터 포맷을 변환하고 라우팅하는 역할을 한다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-H와 CAN-L 두 신호선이 서로 단락(Short)되었을 때, 버스 상태에 미치는 영향은?",
    options: ["CAN-H 라인이 통신을 이어받는다.", "버스 전체가 Dominant 상태로 고정된다.", "버스 전체가 Recessive 상태로 고정되어 통신 불능 상태가 된다.", "통신 속도가 절반으로 줄어든다."],
    answer: 2,
    explain: "두 라인이 단락되면 차동 전압이 0V에 가까워져 Recessive 상태와 유사하게 되며, 통신 신호를 구별할 수 없어 통신 불능 상태가 된다.",
  },
  {
    question: "LIN 통신 프레임에서 슬레이브 노드가 마스터에게 데이터를 전송하기 위해 필요한 필드를 포함하는 것은?",
    options: ["Sync Break", "Sync Field", "Response (응답)", "Header (헤더)"],
    answer: 2,
    explain: "슬레이브 노드는 마스터가 보낸 헤더(ID 포함)에 응답하여 Data Field와 Checksum Field를 포함하는 Response(응답)를 전송한다.",
  },
  {
    question: "CAN 통신에서 메시지 프레임의 끝을 알리고 다음 프레임 전송을 위한 휴지 기간을 표시하는 필드는?",
    options: ["Data Length Code (DLC)", "Arbitration Field", "End of Frame (EOF)", "Interframe Space (IFS)"],
    answer: 3,
    explain: "Interframe Space(IFS)는 메시지 프레임 전송 완료 후 다음 메시지 전송 시작까지의 버스 휴지 기간을 의미한다.",
  },
  {
    question: "FlexRay 통신에서 'Time Slot'의 길이(duration)는 누가 결정하는가?",
    options: ["각 노드의 데이터 길이", "버스상의 오류 발생 빈도", "시스템 설계 시 통신 매트릭스에 의해 고정", "노드의 전원 전압"],
    answer: 2,
    explain: "FlexRay는 Time-triggered 통신이므로, Time Slot의 길이는 네트워크 설계 단계에서 정의된 통신 매트릭스에 의해 엄격하게 고정된다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드의 클럭 동기화에 사용되는 'Sync Field'는 몇 바이트로 구성되는가?",
    options: ["1 바이트 (0x55)", "2 바이트 (0xAA)", "4 바이트 (0x00)", "8 바이트 (0xFF)"],
    answer: 0,
    explain: "Sync Field는 1바이트(8비트)로, 비트 타이밍 동기화를 위해 패턴 0x55 (01010101)를 사용한다.",
  },
  {
    question: "CAN 통신에서 전송 오류 카운터가 127을 초과하고 수신 오류 카운터가 0일 때, 해당 ECU의 오류 상태는?",
    options: ["Error Active", "Error Passive", "Bus-Off", "Bus-On"],
    answer: 1,
    explain: "전송 또는 수신 오류 카운터 중 하나라도 127을 초과하면 Error Passive 상태로 진입한다.",
  },
  {
    question: "자동차 ECU 플래시 프로그래밍과 같이 대용량 데이터 전송에 높은 대역폭을 제공하는 프로토콜이 가장 유리한 것은?",
    options: ["LIN", "CAN", "FlexRay", "K-Line"],
    answer: 2,
    explain: "FlexRay는 CAN이나 LIN보다 훨씬 높은 통신 속도(최대 10Mbps)를 제공하여 대용량 데이터 전송에 유리하다.",
  },
  {
    question: "CAN 통신 프레임의 ACK 필드(Acknowledge Field)에서 수신 ECU가 전송에 성공했음을 알리기 위해 전송하는 비트는?",
    options: ["Dominant 비트 (논리 '0')", "Recessive 비트 (논리 '1')", "Parity Bit", "Start Bit"],
    answer: 0,
    explain: "성공적으로 메시지를 수신한 ECU는 송신 ECU가 보낸 Recessive 비트를 Dominant 비트로 덮어써서 수신 성공을 알린다.",
  },
  {
    question: "CAN 통신에서 Bit Stuffing이 이루어지는 필드가 아닌 것은?",
    options: ["Arbitration Field", "Data Field", "CRC Field", "CRC Delimiter Field"],
    answer: 3,
    explain: "Bit Stuffing은 메시지의 동기화와 오류 검출을 위해 Arbitation Field부터 CRC Field까지 적용되며, Delimiter와 EOF, IFS 등에는 적용되지 않는다.",
  },
  {
    question: "LIN 통신에서 슬립 모드(Sleep Mode)를 해제하고 다시 통신을 시작하도록 하는 신호는?",
    options: ["Sync Field", "Wakeup Signal", "Checksum Field", "ID Field"],
    answer: 1,
    explain: "슬립 모드에 진입한 LIN 노드는 버스상의 Wakeup Signal(기존 비트보다 긴 Dominant 펄스)을 감지하고 다시 통신에 참여한다.",
  },
  {
    question: "FlexRay 통신에서 'Static Segment'에서 메시지 전송 시 충돌이 발생하지 않는 주된 이유는?",
    options: ["Dominant/Recessive 중재 사용", "Single-wire 통신", "메시지 ID 우선순위 사용", "미리 할당된 Time Slot 사용"],
    answer: 3,
    explain: "Static Segment에서는 각 노드가 지정된 Time Slot에만 전송을 허용하므로 메시지 간의 충돌 자체가 발생하지 않는다.",
  },
  {
    question: "CAN 통신에서 두 개 이상의 ECU가 동시에 메시지 전송을 시도할 때, ID가 낮은 ECU가 우선권을 갖는 통신 방식은?",
    options: ["Time-triggered", "Master-slave", "Token passing", "Non-Destructive Arbitration"],
    answer: 3,
    explain: "CAN은 비파괴적 중재(Non-Destructive Arbitration)를 통해 메시지 ID를 비교하며, ID가 낮은(Dominant 비트가 많은) 메시지가 버스 제어권을 갖는다.",
  },
  {
    question: "자동차 ECU 간의 통신에서 LIN 통신이 주로 사용되는 영역으로 가장 적합한 것은?",
    options: ["파워트레인 및 샤시 제어", "안전 제어 시스템(ABS, ESC)", "도어 잠금 장치, 창문 제어, 미러 등 저속 편의 장치 제어", "차량 진단 및 플래시 프로그래밍"],
    answer: 2,
    explain: "LIN은 저속, 저비용 구현이 가능하여 도어 모듈, 에어컨 제어, 라이트 스위치 등 비핵심 편의 장치 제어에 주로 사용된다.",
  },
  {
    question: "CAN 통신에서 Recessive 비트 상태 시, CAN-H와 CAN-L의 차동 전압(Vd = Vh - Vl)은?",
    options: ["약 2V", "약 -2V", "약 0V", "약 5V"],
    answer: 2,
    explain: "Recessive 상태는 두 라인 모두 약 2.5V로 동일하여 차동 전압이 0V에 가깝고, 버스 휴지 상태를 나타낸다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment'에서 메시지 전송 시 충돌을 방지하기 위해 사용하는 기법은?",
    options: ["메시지 ID 기반의 중재", "Master-slave 제어", "시간 기반의 Mini-slot을 이용한 중재", "토큰 패싱"],
    answer: 2,
    explain: "Dynamic Segment는 유연성을 위해 Mini-slot을 사용하며, 노드가 전송을 원할 경우 Mini-slot을 선점하여 메시지 충돌을 방지한다.",
  },
  {
    question: "LIN 통신 프레임에서 마스터 노드가 슬레이브 노드에 데이터 전송을 요청하는 필드는?",
    options: ["Data Field", "CRC Field", "ID Field (식별자)", "Sync Field"],
    answer: 2,
    explain: "LIN은 마스터가 식별자(ID)를 포함한 헤더(Header)를 전송하면, 해당 ID에 응답하는 슬레이브가 데이터와 체크섬을 전송하는 방식으로 통신한다.",
  },
  {
    question: "CAN 통신에서 Form Error(형식 오류)가 발생하는 필드로 옳지 않은 것은?",
    options: ["Start of Frame Field", "ACK Delimiter Field", "CRC Delimiter Field", "Data Field"],
    answer: 3,
    explain: "Form Error는 CAN 프레임의 고정된 형식(Delimiters, EOF, SOF 등)이나 Bit Stuffing 규칙 위반 시 발생하며, Data Field 자체의 오류는 CRC Error나 Bit Error로 검출될 수 있다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-H 라인이 단선(Open)되었을 때, 버스 상태에 미치는 영향은?",
    options: ["통신이 완전히 중단된다.", "버스 전체가 Dominant 상태로 고정된다.", "차동 신호 대신 단일 종단 신호로 통신 속도가 저하되거나 오류 발생", "CAN-L이 전압 레벨을 2배로 높여 통신을 이어간다."],
    answer: 2,
    explain: "한 선 단선 시 일시적으로 단일 종단 신호처럼 작동하려 시도하나, 외부 노이즈에 취약해져 통신 오류가 발생하거나 중단된다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Error Passive' 상태로 복귀하는 조건은?",
    options: ["전송 오류 카운터가 0이 될 때", "수신 오류 카운터가 0이 될 때", "전송 또는 수신 오류 카운터가 127 이하로 감소할 때", "Bus-Off 상태에서 복귀할 때"],
    answer: 2,
    explain: "전송 및 수신 오류 카운터가 127 이하로 떨어지면 Error Passive 상태로 복귀한다.",
  },
  {
    question: "FlexRay 통신에서 'Static Segment'의 타임 슬롯은 누가 소유하며 데이터를 전송하는가?",
    options: ["가장 높은 ID를 가진 ECU", "가장 낮은 ID를 가진 ECU", "통신 매트릭스에 지정된 단 하나의 ECU", "선착순으로 메시지를 전송하는 ECU"],
    answer: 2,
    explain: "Static Segment의 타임 슬롯은 시스템 설계 시 특정 ECU에게만 할당되어 해당 ECU만 그 시간에 데이터를 전송한다.",
  },
  {
    question: "LIN 통신에서 'Sync Break' 필드의 비트 시간은 일반적인 데이터 비트 시간보다 얼마나 긴가?",
    options: ["동일하다.", "2배 이상 길다.", "10배 이상 길다.", "13배 이상 길다."],
    answer: 3,
    explain: "Sync Break는 일반 비트 시간의 13배 이상(13Tbit)의 Dominant 레벨로, 슬레이브 노드가 통신 시작과 동기화를 인지하도록 한다.",
  },
  {
    question: "CAN 통신 프레임의 확장 프레임(Extended Frame)에서 메시지 식별자(Identifier)의 총 비트 수는?",
    options: ["11비트", "18비트", "29비트", "64비트"],
    answer: 2,
    explain: "확장 CAN 프레임은 표준 11비트에 18비트 확장 식별자를 추가하여 총 29비트의 식별자를 사용한다.",
  },
  {
    question: "자동차 네트워크에서 높은 대역폭과 이중 채널을 통한 높은 신뢰성이 요구되는 영역에 사용되는 프로토콜은?",
    options: ["LIN", "CAN", "FlexRay", "K-Line"],
    answer: 2,
    explain: "FlexRay는 최대 10Mbps의 높은 대역폭과 이중 채널(Channel A, B)을 통한 이중화(Redundancy)를 제공한다.",
  },
  {
    question: "CAN 통신에서 메시지 전송 후, 수신 ECU가 ACK 필드를 Dominant로 변경하지 않았을 때(ACK 에러) 발생하는 현상은?",
    options: ["메시지가 정상적으로 전송된 것으로 간주", "송신 ECU가 오류 카운터를 증가시키고 메시지 재전송", "버스 전체가 Dominant 상태로 고정", "통신 속도 감소"],
    answer: 1,
    explain: "ACK 에러는 수신 실패를 의미하며, 송신 ECU는 이를 감지하고 오류 카운터를 증가시킨 후 재전송을 시도한다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 슬레이브 노드에게 데이터를 요청하는 필드가 포함된 부분은?",
    options: ["Response (응답)", "Checksum", "Header (헤더)", "Data Field"],
    answer: 2,
    explain: "LIN 헤더는 Sync Break, Sync Field, ID Field로 구성되며, ID Field가 슬레이브 노드에게 데이터 응답을 요청하는 역할을 한다.",
  },
  {
    question: "CAN 통신에서 CAN-H와 CAN-L의 공통 모드 전압(Common Mode Voltage)이 변하는 주된 원인은?",
    options: ["메시지 우선순위 중재", "버스 오류 발생", "ECU의 전원 전압 변화 또는 외부 노이즈 유입", "종단 저항 값의 변화"],
    answer: 2,
    explain: "공통 모드 전압은 외부의 전기적 간섭이나 ECU 전원의 변동에 의해 함께 변동할 수 있다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Bus-Off' 상태로 진입했을 때, ECU가 취하는 조치로 옳은 것은?",
    options: ["오류 메시지를 계속 전송한다.", "메시지 우선순위를 낮춘다.", "버스에서 완전히 격리되어 통신 중단", "Recessive 비트만 전송한다."],
    answer: 2,
    explain: "Bus-Off 상태는 심각한 오류 상태로, 해당 ECU는 버스에 영향을 주지 않도록 통신에서 완전히 격리된다.",
  },
  {
    question: "자동차 네트워크에서 게이트웨이 ECU(Gateway ECU)가 수행하는 역할로 가장 중요한 것은?",
    options: ["ECU의 클럭 동기화", "CAN 버스의 종단 저항 역할", "서로 다른 네트워크 프로토콜 및 속도 간의 데이터 중계 및 변환", "데이터 오류 자동 정정"],
    answer: 2,
    explain: "게이트웨이 ECU는 서로 다른 통신 규격을 가진 네트워크 간에 데이터를 라우팅하고 프로토콜을 변환하는 핵심 역할을 한다.",
  },
  {
    question: "LIN 통신에서 Sync Break 필드가 헤더의 가장 앞에 위치하는 주된 목적은?",
    options: ["데이터 오류 검출", "슬레이브 노드의 물리적인 동기화", "메시지 우선순위 결정", "마스터 노드의 데이터 전송"],
    answer: 1,
    explain: "Sync Break는 일반적인 통신 비트 폭보다 긴 길이로, 슬레이브 노드가 통신 시작을 인지하고 비트 타이밍을 마스터와 동기화하는 데 사용된다.",
  }  
    
];

export const industry010803 = [
{
    question: "CAN 통신에서 ECU가 'Bus-Off' 상태로 진입했을 때, 이 ECU가 다른 ECU의 메시지를 수신할 수 있는가?",
    options: ["Bus-Off 상태에서는 송수신 모두 불가능하다.", "수신은 가능하나, 메시지 전송은 불가능하다.", "송수신 모두 가능하나, 오류 플래그를 전송할 수 없다.", "수신은 불가능하고, 메시지 전송만 가능하다."],
    answer: 1,
    explain: "Bus-Off 상태는 버스에 영향을 주지 않기 위해 메시지 전송은 중단하지만, 버스 모니터링 및 메시지 수신은 계속 가능하다.",
  },
  {
    question: "고속 CAN 통신에서 종단 저항(Termination Resistor)의 주된 역할은 무엇이며, 통상적으로 버스 양 끝단에 설치되는 저항 값은?",
    options: ["버스 전원 공급, 60Ω", "신호 반사 방지, 120Ω", "데이터 오류 검출, 60Ω", "버스 전류 제한, 120Ω"],
    answer: 1,
    explain: "종단 저항은 통신선의 임피던스 정합을 통해 신호 반사를 방지하며, 고속 CAN에서는 일반적으로 120Ω 저항 두 개를 버스 양 끝에 설치하여 병렬 60Ω을 만든다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 슬립 모드(Sleep Mode)로 진입하는 주된 조건은?",
    options: ["버스 전압이 12V 이하일 때", "슬레이브 노드 스스로 결정", "버스에 데이터 통신이 4초 이상 없을 때", "마스터 노드가 Wakeup Signal을 전송했을 때"],
    answer: 2,
    explain: "LIN 프로토콜에서는 버스 통신이 일정 시간(보통 4초) 동안 없을 경우, 노드의 전력 절감을 위해 슬립 모드로 자동 진입한다.",
  },
  {
    question: "FlexRay 통신에서 'Cycle(사이클)' 내에서 Static Segment(정적 세그먼트)가 Dynamic Segment(동적 세그먼트)보다 먼저 배치되는 주된 이유는?",
    options: ["동적 세그먼트의 유연성 확보", "시간 보장형 메시지의 실시간성 확보", "메시지 우선순위 중재", "전력 소비 최소화"],
    answer: 1,
    explain: "Static Segment는 시간 보장이 필수적인 핵심 메시지를 전송하므로, Cycle의 시작 부분에 배치하여 실시간성을 최우선으로 확보한다.",
  },
  {
    question: "CAN 통신에서 ECU의 트랜시버가 CAN-H 라인에만 지속적인 단락(Short to Ground)을 발생시켰을 때, 버스의 차동 전압 파형은?",
    options: ["파형의 진폭이 2배로 증가", "파형의 진폭이 감소하고 Dominant 상태로 고정", "파형의 주파수만 감소", "파형이 Recessive 상태로 고정"],
    answer: 1,
    explain: "CAN-H가 접지 단락되면 CAN-H 전위가 낮아져 차동 전압이 감소하면서 Dominant 상태를 유지하려 하여 통신 불능 상태가 된다.",
  },
  {
    question: "LIN 통신 프레임의 헤더(Header)에서 Sync Field(동기 필드) 다음에 위치하며, 마스터가 슬레이브에게 데이터 응답을 요청하는 필드는?",
    options: ["Data Field", "CRC Field", "Identifier Field (식별자)", "Sync Break"],
    answer: 2,
    explain: "마스터는 Sync Break와 Sync Field 다음에 Identifier Field(ID)를 전송하여, 해당 ID를 가진 슬레이브 노드의 데이터 응답을 유도한다.",
  },
  {
    question: "FlexRay 통신의 특징 중, CAN 통신과 가장 뚜렷하게 구별되는 기술적인 특징은?",
    options: ["높은 전송 속도", "비파괴적 중재(Arbitration)", "메시지 ID 우선순위", "시간 동기화 및 결정론적(Time-Triggered) 통신"],
    answer: 3,
    explain: "FlexRay의 핵심은 엄격한 시간 동기화를 기반으로 한 결정론적 통신이며, 이는 CAN의 충돌 기반 비파괴적 중재 방식과 근본적으로 다르다.",
  },
  {
    question: "CAN 통신에서 Recessive 비트 상태 시, CAN-H와 CAN-L의 공통 모드 전압(Common Mode Voltage)은 일반적으로 몇 V 인가?",
    options: ["0V", "1.5V", "2.5V", "3.5V"],
    answer: 2,
    explain: "Recessive 상태는 버스 휴지 상태로, CAN-H와 CAN-L 모두 공통 모드 전압인 약 2.5V를 유지하여 차동 전압이 0V에 가깝다.",
  },
  {
    question: "OBD-II 진단에서 차량과 진단기 간의 통신에 UDS(Unified Diagnostic Services)가 사용될 때, 해당 프로토콜을 통칭하는 용어는?",
    options: ["KWP 2000", "J1850", "DoCAN (Diagnostics over CAN)", "ISO 9141"],
    answer: 2,
    explain: "DoCAN은 CAN 통신 프로토콜을 기반으로 UDS(ISO 14229) 진단 메시지를 전송하는 방식을 의미한다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 슬레이브 노드에 데이터 응답을 요청하는 헤더를 전송할 때, 슬레이브 노드가 응답하는 프레임의 부분은?",
    options: ["Sync Break", "Sync Field", "Header (헤더)", "Response (응답)"],
    answer: 3,
    explain: "마스터의 헤더 수신 후, 해당 슬레이브는 Data Field와 Checksum Field를 포함하는 Response(응답)를 전송한다.",
  },
  {
    question: "CAN 통신 프레임의 ACK 필드(Acknowledge Field)에서 수신 ECU가 전송에 성공했음을 알리기 위해 전송하는 비트는?",
    options: ["논리값 '1' (Recessive)", "논리값 '0' (Dominant)", "Parity Bit", "Start Bit"],
    answer: 1,
    explain: "성공적으로 메시지를 수신한 ECU는 송신 ECU가 보낸 Recessive 비트를 Dominant 비트로 덮어써서 수신 성공을 알린다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드의 데이터 전송이 지연되거나 누락되는 주된 오류 유형은?",
    options: ["Form Error", "Stuff Error", "Frame Error (응답 지연)", "CRC Error"],
    answer: 2,
    explain: "마스터가 헤더를 전송했음에도 불구하고, 슬레이브 노드의 응답(Response)이 지정된 시간 내에 오지 않거나 누락될 때 Frame Error로 간주된다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment(동적 세그먼트)'의 타임 슬롯이 유동적으로 할당되는 주된 이유는?",
    options: ["시간 보장형 메시지 전송", "버스 종단 저항 제어", "비주기적 이벤트 메시지의 유연한 처리", "통신 속도 증가"],
    answer: 2,
    explain: "Dynamic Segment는 Static Segment의 시간 보장형 메시지와 달리, 에어백 전개와 같은 비주기적인 이벤트 데이터를 유연하게 처리하기 위해 사용된다.",
  },
  {
    question: "CAN 통신에서 ECU의 트랜시버가 CAN-L 라인에만 지속적인 단락(Short to Ground)을 발생시켰을 때, 버스의 차동 전압 파형은?",
    options: ["파형의 진폭이 2배로 증가", "파형의 진폭이 감소하고 Dominant 상태로 고정", "파형의 주파수만 감소", "파형이 Recessive 상태로 고정"],
    answer: 1,
    explain: "CAN-L이 접지 단락되면 CAN-L 전위가 낮아져 차동 전압이 Dominant 상태를 유지하려 하여 통신 불능 상태가 된다.",
  },
  {
    question: "LIN 통신의 저비용 구현을 위한 물리 계층의 특징은?",
    options: ["이중 차동선 통신", "광섬유 사용", "단일 차동선 통신", "단일선(Single-wire) 통신"],
    answer: 3,
    explain: "LIN은 저비용을 위해 단일선 통신 방식을 채택하며, 최대 통신 속도는 20kbps로 제한된다.",
  },
  {
    question: "CAN 통신에서 메시지 ID가 낮을수록 우선순위가 높은 통신 방식을 무엇이라고 하는가?",
    options: ["Token Passing", "Master-Slave", "Non-Destructive Arbitration (비파괴적 중재)", "Time-Triggered"],
    answer: 2,
    explain: "CAN은 비파괴적 중재(Non-Destructive Arbitration)를 사용하여 ID가 낮은 메시지가 충돌 없이 버스 제어권을 획득하게 한다.",
  },
  {
    question: "FlexRay 통신에서 두 개의 채널(Channel A, Channel B)을 통해 동일 데이터를 전송하여 신뢰성을 높이는 방법은?",
    options: ["Single-Channel Mode", "Dual-Mode Redundancy (이중화)", "Time-Triggered Slot", "Dynamic Segment"],
    answer: 1,
    explain: "Dual-Mode Redundancy는 두 채널을 사용하여 데이터의 이중화를 통해 하나의 채널에 오류가 발생해도 통신 신뢰성을 유지하게 한다.",
  },
  {
    question: "OBD-II 진단에서 진단기가 ECU에 데이터를 요청할 때 사용하는 서비스 ID(Service ID)는?",
    options: ["$0x01 (요청 데이터 식별)", "$0x02 (요청 DTC)", "$0x03 (요청 데이터 스트림)", "$0x04 (요청 제어)"],
    answer: 0,
    explain: "서비스 ID $0x01은 파워트레인 진단 데이터(PID)를 요청하는 서비스이다. (PID는 Service ID $0x01의 서브 기능)",
  },
  {
    question: "CAN 통신 프레임에서 수신 ECU가 수신된 데이터의 오류 여부를 검사하기 위해 사용하는 필드는?",
    options: ["Arbitration Field", "DLC Field", "CRC Field (순환 중복 검사)", "ACK Field"],
    answer: 2,
    explain: "CRC(Cyclic Redundancy Check) 필드는 전송된 데이터에 기반한 오류 검출 코드를 포함하여 수신 측의 오류 검사를 가능하게 한다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 전송하는 데이터 필드의 최대 길이는 몇 바이트인가?",
    options: ["2 바이트", "4 바이트", "8 바이트", "64 바이트"],
    answer: 1,
    explain: "LIN 데이터 필드는 1바이트부터 8바이트까지 전송할 수 있으며, 일반적인 CAN과 동일하게 최대 8바이트이다.",
  },
  {
    question: "MDPS(전동식 파워 스티어링)와 같은 안전 관련 시스템에 CAN 대신 FlexRay 통신을 사용하는 주된 기술적 이유는?",
    options: ["FlexRay의 저비용 구현", "FlexRay의 시간 동기화 및 결정론적 통신 특성", "FlexRay의 단일선 통신 방식", "FlexRay의 단순한 프레임 구조"],
    answer: 1,
    explain: "FlexRay는 결정론적 통신을 보장하여 데이터 전송 시간이 예측 가능하므로, 높은 실시간성과 안전성이 요구되는 시스템에 적합하다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Error Active(오류 활성)' 상태일 때, 버스에 오류를 알리기 위해 전송하는 Active Error Flag의 비트 길이는?",
    options: ["6 Dominant 비트", "6 Recessive 비트", "8 Recessive 비트", "8 Dominant 비트"],
    answer: 0,
    explain: "Error Active 상태의 ECU는 6개의 Dominant 비트를 전송하여 모든 ECU가 오류를 인지하고 현재 메시지 전송을 강제로 중단하도록 한다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 슬레이브 노드의 응답을 기다리는 동안 발생하는 타임아웃 오류는 주로 어디서 검출되는가?",
    options: ["슬레이브 노드", "CAN 게이트웨이", "마스터 노드", "트랜시버"],
    answer: 2,
    explain: "LIN은 마스터-슬레이브 구조이므로, 마스터 노드가 슬레이브 노드의 응답 지연을 감지하고 타임아웃 오류를 검출한다.",
  },
  {
    question: "FlexRay 통신에서 'Static Segment'에서 메시지 전송 시 충돌이 발생하지 않는 주된 이유는?",
    options: ["Dominant/Recessive 중재 사용", "Single-wire 통신", "메시지 ID 우선순위 사용", "미리 할당된 Time Slot 사용"],
    answer: 3,
    explain: "Static Segment에서는 각 노드가 지정된 Time Slot에만 전송을 허용하므로 메시지 간의 충돌 자체가 발생하지 않는다.",
  },
  {
    question: "CAN 통신에서 CAN-H와 CAN-L 두 신호선이 단락(Short)되었을 때, 버스의 차동 전압 파형은?",
    options: ["파형의 진폭이 2배로 증가", "파형의 진폭이 증가하고 Dominant 상태로 고정", "파형의 주파수만 감소", "파형이 Recessive 상태로 고정되어 차동 전압 0V에 가까워짐"],
    answer: 3,
    explain: "두 라인이 단락되면 차동 전압이 0V에 가까워져 Recessive 상태와 유사하게 되며, 통신 신호를 구별할 수 없어 통신 불능 상태가 된다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 Wakeup Signal을 수신한 후, 통신에 참여하기 위해 수행하는 조치는?",
    options: ["메시지 ID를 마스터에게 전송", "버스 전압을 5V로 고정", "내부 클럭을 마스터와 동기화", "Bus-Off 상태로 진입"],
    answer: 2,
    explain: "Wakeup Signal 수신 후, 슬레이브는 슬립 모드에서 벗어나 통신에 참여하며, Sync Field를 통해 클럭 동기화를 재수행한다.",
  },
  {
    question: "CAN 통신에서 비트 레벨의 위반(예: Stuff Bit 규칙 위반, 프레임 구조의 고정 필드 비트 위반 등)이 감지되었을 때 발생하는 오류 유형은?",
    options: ["Bit Error", "Form Error", "CRC Error", "ACK Error"],
    answer: 1,
    explain: "Form Error(형식 오류)는 CAN 프레임의 고정된 형식(예: Delimiters, EOF, SOF)이나 Bit Stuffing 규칙 위반 시 발생한다.",
  },
  {
    question: "OBD-II 진단에서 '요청 시점의 현재 데이터'를 확인하기 위해 사용하는 서비스 ID와 PID(Parameter ID) 요청 코드는?",
    options: ["$0x01", "$0x02", "$0x03", "$0x04"],
    answer: 0,
    explain: "서비스 ID $0x01은 '요청 시점의 현재 진단 데이터'를 의미하며, PID를 통해 특정 센서 값 등을 요청한다.",
  },
  {
    question: "FlexRay 통신 프레임에서 메시지 전송 시 충돌이 발생하면, 이는 주로 어느 세그먼트에서 발생할 수 있는가?",
    options: ["Static Segment", "Cycle", "Dynamic Segment", "Startup Frame"],
    answer: 2,
    explain: "Dynamic Segment는 유연성을 위해 Mini-slot을 사용하며, 노드가 동시에 전송을 시도할 경우 충돌이 발생할 수 있다. Static Segment는 충돌이 발생하지 않는다.",
  },
  {
    question: "CAN 통신에서 전송 오류 카운터가 255를 초과하여 ECU가 Bus-Off 상태로 진입했을 때, 이 ECU가 다시 Bus-On 상태로 복귀하기 위해 만족해야 하는 가장 중요한 조건은?",
    options: ["전송 오류 카운터를 0으로 초기화", "메시지 우선순위를 낮춘다.", "Recessive 비트를 128회 연속 감지", "CAN 버스를 5초간 모니터링"],
    answer: 2,
    explain: "Bus-Off 상태의 ECU는 버스가 128회 연속 Recessive 비트(버스 휴지 상태)임을 감지해야만 다시 Bus-On(Error Passive) 상태로 복귀할 수 있다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 슬레이브 노드에 데이터 전송을 요청하는 필드가 포함된 부분은?",
    options: ["Response (응답)", "Checksum", "Header (헤더)", "Data Field"],
    answer: 2,
    explain: "LIN 헤더는 Sync Break, Sync Field, ID Field로 구성되며, ID Field가 슬레이브 노드에게 데이터 응답을 요청하는 역할을 한다.",
  },
  {
    question: "FlexRay 통신에서 'Cycle'이 갖는 가장 중요한 의미는?",
    options: ["단일 메시지 전송 시간", "통신 속도", "Static Segment와 Dynamic Segment를 모두 포함하는 전체 통신 주기", "오류 발생 시 재전송 횟수"],
    answer: 2,
    explain: "FlexRay 사이클은 정적 세그먼트와 동적 세그먼트, 그리고 가드 시간 등을 포함하는 전체 반복 통신 주기를 의미하며, 시간 동기화의 기본 단위이다.",
  },
  {
    question: "CAN 통신에서 Dominant 비트 상태 시, CAN-H와 CAN-L의 차동 전압(Vd = Vh - Vl)은?",
    options: ["약 2V", "약 -2V", "약 0V", "약 5V"],
    answer: 0,
    explain: "Dominant 상태는 CAN-H가 약 3.5V, CAN-L이 약 1.5V를 유지하여 차동 전압이 약 2V가 된다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드의 클럭 동기화에 사용되는 'Sync Field'는 몇 바이트로 구성되며, 사용하는 패턴은?",
    options: ["1 바이트, 0xAA", "1 바이트, 0x55", "2 바이트, 0xFF", "4 바이트, 0x00"],
    answer: 1,
    explain: "Sync Field는 1바이트(8비트)로, 비트 타이밍 동기화를 위해 패턴 0x55 (01010101)를 사용한다.",
  },
  {
    question: "CAN 통신에서 CRC 에러(순환 중복 검사 오류)가 발생했다면, 이는 주로 어느 필드에서 발생한 오류를 의미하는가?",
    options: ["Arbitration Field", "ACK Field", "Data Field 또는 CRC Field 자체", "Start of Frame Field"],
    answer: 2,
    explain: "CRC 에러는 Data Field와 CRC Field 자체를 포함한 전송 데이터에 오류가 발생하여 수신 측에서 계산한 값과 수신한 CRC 값이 일치하지 않을 때 발생한다.",
  },
  {
    question: "OBD-II 진단에서 '저장된 고장 코드(DTC)'를 확인하기 위해 사용하는 서비스 ID는?",
    options: ["$0x01", "$0x02", "$0x03", "$0x04"],
    answer: 2,
    explain: "서비스 ID $0x03은 '저장된 고장 코드(Diagnostic Trouble Code, DTC)'를 요청하는 서비스이다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment'의 유연한 타임 슬롯 할당 방식에서 메시지 충돌을 방지하기 위해 사용하는 기법은?",
    options: ["메시지 ID 기반의 중재", "Master-slave 제어", "시간 기반의 Mini-slot을 이용한 중재", "토큰 패싱"],
    answer: 2,
    explain: "Dynamic Segment는 유연성을 위해 Mini-slot을 사용하며, 노드가 전송을 원할 경우 Mini-slot을 선점하여 메시지 충돌을 방지한다.",
  },
  {
    question: "CAN 통신에서 Bit Stuffing 규칙 위반(연속 6개 동일 레벨 비트 발생)이 감지되었을 때 발생하는 오류 유형은?",
    options: ["Bit Error", "Stuff Error", "Form Error", "CRC Error"],
    answer: 1,
    explain: "Stuff Error(스터프 오류)는 Bit Stuffing 규칙에 따라 삽입되어야 할 비트가 없거나, 연속 5개 이상의 동일 비트 레벨이 발생하는 경우에 검출된다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 데이터를 전송하는 시점은?",
    options: ["마스터 노드가 버스가 비었음을 알릴 때", "슬레이브 노드 스스로 데이터 전송이 필요할 때", "마스터 노드가 해당 슬레이브의 ID를 포함한 헤더를 전송했을 때", "Sync Break 신호가 감지되었을 때"],
    answer: 2,
    explain: "LIN은 마스터가 스케줄에 따라 ID를 포함한 헤더를 전송하면, 해당 ID에 응답하는 슬레이브가 데이터와 체크섬을 이어서 전송한다.",
  },
  {
    question: "CAN 통신에서 CAN-H와 CAN-L 두 신호선이 단선(Open)되었을 때, 버스의 차동 전압 파형은?",
    options: ["차동 전압이 0V에 가까워져 통신 불능", "차동 전압이 2배로 증가", "차동 신호 대신 단일 종단 신호로 통신 속도가 저하되거나 오류 발생", "CAN-L이 전압 레벨을 2배로 높여 통신을 이어간다."],
    answer: 2,
    explain: "고속 CAN은 차동 신호에 의존하지만, 두 선 모두 단선되면 통신 자체가 거의 불가능해지며, 심각한 오류가 발생한다.",
  }  
];

export const industry010804 = [
{
    question: "고속 CAN 통신에서 버스 종단 저항(Termination Resistor)이 규정 값(60Ω)보다 현저히 높은 상태(예: 120Ω 이상)일 때, 나타나는 주된 통신 문제는?",
    options: ["버스 전체가 Dominant 상태로 고정된다.", "통신 속도가 2배로 증가한다.", "버스에서 신호 반사가 발생하여 파형 왜곡이 심해진다.", "ECU의 전력 소비가 증가한다."],
    answer: 2,
    explain: "종단 저항이 높으면 임피던스 정합이 불량해져 신호가 통신선 끝에서 반사되어 원래 신호와 겹쳐 파형 왜곡(링잉 현상)을 일으킨다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 데이터를 전송하기 전에 마스터 노드가 전송하는 필드를 순서대로 나열한 것은?",
    options: ["Sync Field - Sync Break - Identifier Field", "Identifier Field - Data Field - Checksum Field", "Sync Field - Identifier Field - Checksum Field", "Sync Break - Sync Field - Identifier Field"],
    answer: 3,
    explain: "LIN 헤더는 Sync Break로 시작을 알리고, Sync Field로 클럭 동기화를 하며, Identifier Field로 응답할 슬레이브를 지정한다.",
  },
  {
    question: "FlexRay 통신에서 'Startup Frame(시작 프레임)'을 전송하는 주된 목적은?",
    options: ["비주기적인 이벤트 데이터 전송", "통신 속도 조절", "버스상의 모든 노드의 동기화(Sync) 및 클럭 동기", "메시지 우선순위 중재"],
    answer: 2,
    explain: "Startup Frame은 FlexRay 통신 사이클의 시작을 알리고, 버스상의 모든 노드의 시간 동기화를 확립하는 데 사용된다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Error Passive' 상태일 때, 해당 ECU가 전송하는 오류 플래그(Error Flag)의 특징은?",
    options: ["6개의 Dominant 비트", "8개의 Dominant 비트", "6개의 Recessive 비트", "8개의 Recessive 비트"],
    answer: 3,
    explain: "Error Passive 상태의 ECU는 8개의 Recessive 비트를 전송하여, 다른 ECU의 통신에 미치는 영향을 최소화한다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, ECU에 저장된 영구적인 고장 코드(DTC)를 지우도록 요청하는 서비스 ID는?",
    options: ["$0x03", "$0x04", "$0x14", "$0x19"],
    answer: 1,
    explain: "서비스 ID $0x04는 'Clear Diagnostic Information'으로, ECU에 저장된 고장 코드 및 관련 데이터를 삭제하도록 요청한다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-H와 CAN-L이 모두 접지(Ground)에 단락(Short to Ground)되었을 때, 나타나는 현상은?",
    options: ["버스 전체가 Dominant 상태로 고정된다.", "통신 속도가 절반으로 줄어든다.", "버스 전체가 Recessive 상태로 고정되어 통신 불능", "CAN 통신이 정상적으로 작동한다."],
    answer: 2,
    explain: "두 라인이 모두 접지에 단락되면 두 전위 모두 0V에 가까워져 차동 전압이 0V가 되므로 Recessive 상태와 유사하게 되어 통신 불능이 된다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 슬립 모드에서 벗어나기 위해 수신해야 하는 Wakeup Signal의 특징은?",
    options: ["Sync Break 신호와 동일하다.", "일반 비트보다 짧은 Dominant 펄스이다.", "일반 비트보다 긴 Dominant 펄스이다.", "Recessive 비트만 연속된다."],
    answer: 2,
    explain: "Wakeup Signal은 일반적인 데이터 비트 폭보다 긴 Dominant 펄스 형태로 전송되어, 슬립 상태의 노드가 통신 시작을 감지하도록 한다.",
  },
  {
    question: "FlexRay 통신에서 'Static Segment'의 타임 슬롯이 결정론적(Deterministic) 특성을 갖는 주된 이유는?",
    options: ["버스 전압이 항상 5V로 유지되기 때문에", "메시지 ID가 낮은 것이 우선순위를 갖기 때문에", "타임 슬롯이 시스템 설계 시 미리 할당되고 고정되기 때문에", "메시지 길이가 유동적이기 때문에"],
    answer: 2,
    explain: "결정론적 통신은 메시지 전송 시간이 예측 가능하다는 의미이며, Static Segment는 시간 슬롯이 고정되어 이 특성을 보장한다.",
  },
  {
    question: "CAN 통신에서 메시지 ID가 낮은 ECU가 메시지 충돌 시 우선권을 갖는 통신 방식을 무엇이라고 하는가?",
    options: ["Time-Triggered", "Master-Slave", "Token Passing", "Non-Destructive Arbitration (비파괴적 중재)"],
    answer: 3,
    explain: "CAN은 Dominant/Recessive 논리를 이용한 비파괴적 중재를 통해 ID가 낮은(우선순위 높은) 메시지가 버스 제어권을 획득한다.",
  },
  {
    question: "자동차 네트워크에서 서로 다른 CAN 버스(예: 파워트레인 CAN과 바디 CAN) 간의 통신을 중계하는 장치는?",
    options: ["Transceiver", "Termination Resistor", "Gateway ECU", "CAN Controller"],
    answer: 2,
    explain: "Gateway ECU(게이트웨이 ECU)는 서로 다른 네트워크 프로토콜이나 속도를 가진 CAN 버스 사이에서 데이터 포맷을 변환하고 라우팅하는 역할을 한다.",
  },
  {
    question: "LIN 통신 프레임의 체크섬(Checksum) 필드가 보장하는 오류 제어 방식은?",
    options: ["데이터 오류 자동 정정", "메시지 우선순위 검증", "전송 데이터의 오류 검출", "슬레이브 노드의 응답 시간 검증"],
    answer: 2,
    explain: "LIN 체크섬은 데이터 필드를 포함한 특정 필드 값을 기반으로 계산되어 전송되며, 수신 측에서 동일 계산 후 비교하여 데이터의 오류 발생 여부를 검출한다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment'의 타임 슬롯은 누가 소유하며 데이터를 전송하는가?",
    options: ["가장 높은 ID를 가진 ECU", "가장 낮은 ID를 가진 ECU", "통신 매트릭스에 지정된 단 하나의 ECU", "메시지 전송이 필요한 노드들이 선점 방식으로 사용"],
    answer: 3,
    explain: "Dynamic Segment는 유연성을 위해 Mini-slot을 사용하며, 메시지 전송이 필요한 노드가 선점 방식으로 타임 슬롯을 사용한다.",
  },
  {
    question: "CAN 통신에서 전송 오류 카운터가 255를 초과하여 ECU가 Bus-Off 상태로 진입했을 때, 이 ECU가 다시 Bus-On 상태로 복귀하기 위해 만족해야 하는 가장 중요한 조건은?",
    options: ["전송 오류 카운터를 0으로 초기화", "메시지 우선순위를 낮춘다.", "Recessive 비트를 128회 연속 감지", "CAN 버스를 5초간 모니터링"],
    answer: 2,
    explain: "Bus-Off 상태의 ECU는 버스가 128회 연속 Recessive 비트(버스 휴지 상태)임을 감지해야만 다시 Bus-On(Error Passive) 상태로 복귀할 수 있다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, ECU가 제공하는 현재 데이터 스트림(Live Data)을 요청하는 서비스 ID는?",
    options: ["$0x01", "$0x02", "$0x03", "$0x04"],
    answer: 0,
    explain: "서비스 ID $0x01은 'Request Current Powertrain Diagnostic Data'로, 엔진 RPM, 온도 등 현재의 파라미터 ID(PID) 값을 요청한다.",
  },
  {
    question: "고속 CAN 통신에서 버스 종단 저항(Termination Resistor)이 규정 값(60Ω)보다 현저히 낮은 상태(예: 30Ω 이하)일 때, 나타나는 주된 통신 문제는?",
    options: ["버스에 흐르는 전류가 과도하게 증가하여 트랜시버에 부하 발생", "신호 반사가 발생하여 파형 왜곡이 심해진다.", "버스 전체가 Recessive 상태로 고정된다.", "통신 속도가 감소한다."],
    answer: 0,
    explain: "저항이 낮아지면 버스의 총 전류가 증가하여 트랜시버에 과도한 부하가 걸리고 신호 전압 레벨이 낮아져 통신이 어려워진다.",
  },
  {
    question: "LIN 통신에서 슬립 모드(Sleep Mode)를 해제하고 다시 통신을 시작하도록 하는 신호는?",
    options: ["Sync Field", "Wakeup Signal", "Checksum Field", "ID Field"],
    answer: 1,
    explain: "슬립 모드에 진입한 LIN 노드는 버스상의 Wakeup Signal(긴 Dominant 펄스)을 감지하고 다시 통신에 참여한다.",
  },
  {
    question: "FlexRay 통신에서 높은 신뢰성을 확보하기 위해 사용하는 방법 중 하나로, 두 개의 채널(Channel A, Channel B)을 이용하여 동일 데이터를 전송하는 방식은?",
    options: ["Single-Channel Mode", "Dual-Mode Redundancy", "Time-Triggered Slot", "Dynamic Segment"],
    answer: 1,
    explain: "Dual-Mode Redundancy는 두 개의 독립된 채널을 통해 동일한 데이터를 전송하여 하나의 채널에 오류가 발생하더라도 통신을 유지할 수 있게 한다.",
  },
  {
    question: "CAN 통신에서 메시지 전송 후, 수신 ECU가 ACK 필드를 Dominant로 변경하지 않았을 때(ACK 에러), 송신 ECU가 취하는 조치는?",
    options: ["메시지 전송을 중단하고 Bus-Off 상태로 진입", "다음 메시지를 전송", "오류 카운터를 증가시키고 메시지를 재전송", "통신 속도를 낮춘다."],
    answer: 2,
    explain: "ACK 에러는 메시지가 정상적으로 수신되지 않았음을 의미하며, 송신 ECU는 오류 카운터를 증가시키고 해당 메시지를 재전송한다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, '특정 진단 기능의 제어'를 요청하는 서비스 ID는?",
    options: ["$0x14", "$0x22", "$0x27", "$0x2F"],
    answer: 3,
    explain: "서비스 ID $0x2F는 'InputOutputControlByIdentifier'로, 특정 부품의 작동을 활성화/비활성화하거나 값을 변경하는 제어 기능을 요청한다.",
  },
  {
    question: "CAN 통신에서 Dominant 비트 상태 시, CAN-H와 CAN-L의 차동 전압(Vd = Vh - Vl)은?",
    options: ["약 2V", "약 -2V", "약 0V", "약 5V"],
    answer: 0,
    explain: "Dominant 상태는 CAN-H가 약 3.5V, CAN-L이 약 1.5V를 유지하여 차동 전압이 약 2V가 된다.",
  },
  {
    question: "LIN 통신 프레임에서 슬레이브 노드의 데이터 전송이 지연되거나 누락되는 주된 오류 유형은?",
    options: ["Form Error", "Stuff Error", "Frame Error (응답 지연)", "CRC Error"],
    answer: 2,
    explain: "마스터가 헤더를 전송했음에도 불구하고, 슬레이브 노드의 응답(Response)이 지정된 시간 내에 오지 않거나 누락될 때 Frame Error로 간주된다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment'의 유연한 타임 슬롯 할당 방식에서 메시지 충돌을 방지하기 위해 사용하는 기법은?",
    options: ["메시지 ID 기반의 중재", "Master-slave 제어", "시간 기반의 Mini-slot을 이용한 중재", "토큰 패싱"],
    answer: 2,
    explain: "Dynamic Segment는 유연성을 위해 Mini-slot을 사용하며, 노드가 전송을 원할 경우 Mini-slot을 선점하여 메시지 충돌을 방지한다.",
  },
  {
    question: "CAN 통신에서 ECU의 트랜시버가 CAN-H 라인에만 지속적인 단락(Short to VCC)을 발생시켰을 때, 버스의 차동 전압 파형은?",
    options: ["파형의 진폭이 감소하고 Dominant 상태로 고정", "파형의 진폭이 감소하고 Recessive 상태로 고정", "파형의 주파수만 감소", "파형이 Recessive 상태로 고정"],
    answer: 1,
    explain: "CAN-H가 VCC에 단락되면 CAN-H와 CAN-L의 전압 차이가 줄어들어 Recessive 상태를 유지하려 하여 통신 불능 상태가 된다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, '저장된 고장 코드(DTC)'를 확인하기 위해 사용하는 서비스 ID는?",
    options: ["$0x01", "$0x02", "$0x03", "$0x04"],
    answer: 2,
    explain: "서비스 ID $0x03은 '저장된 고장 코드(Diagnostic Trouble Code, DTC)'를 요청하는 서비스이다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 슬립 모드(Sleep Mode)로 진입하는 주된 조건은?",
    options: ["버스 전압이 12V 이하일 때", "슬레이브 노드 스스로 결정", "버스에 데이터 통신이 4초 이상 없을 때", "마스터 노드가 Wakeup Signal을 전송했을 때"],
    answer: 2,
    explain: "LIN 프로토콜에서는 버스 통신이 일정 시간(보통 4초) 동안 없을 경우, 노드의 전력 절감을 위해 슬립 모드로 자동 진입한다.",
  },
  {
    question: "FlexRay 통신에서 'Static Segment'의 타임 슬롯이 결정론적(Deterministic) 특성을 갖는 주된 이유는?",
    options: ["버스 전압이 항상 5V로 유지되기 때문에", "메시지 ID가 낮은 것이 우선순위를 갖기 때문에", "타임 슬롯이 시스템 설계 시 미리 할당되고 고정되기 때문에", "메시지 길이가 유동적이기 때문에"],
    answer: 2,
    explain: "결정론적 통신은 메시지 전송 시간이 예측 가능하다는 의미이며, Static Segment는 시간 슬롯이 고정되어 이 특성을 보장한다.",
  },
  {
    question: "CAN 통신에서 메시지 프레임의 끝을 알리고 다음 프레임 전송을 위한 휴지 기간을 표시하는 필드는?",
    options: ["Data Length Code (DLC)", "Arbitration Field", "End of Frame (EOF)", "Interframe Space (IFS)"],
    answer: 3,
    explain: "Interframe Space(IFS)는 메시지 프레임 전송 완료 후 다음 메시지 전송 시작까지의 버스 휴지 기간을 의미한다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, 'ECU의 식별 정보(예: 부품 번호, 소프트웨어 버전)'를 요청하는 서비스 ID는?",
    options: ["$0x10", "$0x14", "$0x22", "$0x27"],
    answer: 2,
    explain: "서비스 ID $0x22는 'ReadDataByIdentifier'로, ECU의 메모리나 식별 정보(예: VIN, 부품 번호)를 요청한다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-H와 CAN-L이 모두 전원(VCC)에 단락(Short to VCC)되었을 때, 나타나는 현상은?",
    options: ["버스 전체가 Dominant 상태로 고정된다.", "통신 속도가 절반으로 줄어든다.", "버스 전체가 Recessive 상태로 고정되어 통신 불능", "CAN 통신이 정상적으로 작동한다."],
    answer: 2,
    explain: "두 라인이 모두 VCC에 단락되면 두 전위 모두 높아져 차동 전압이 0V가 되므로 Recessive 상태와 유사하게 되어 통신 불능이 된다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 슬레이브 노드에 데이터 전송을 요청하는 필드가 포함된 부분은?",
    options: ["Response (응답)", "Checksum", "Header (헤더)", "Data Field"],
    answer: 2,
    explain: "LIN 헤더는 Sync Break, Sync Field, ID Field로 구성되며, ID Field가 슬레이브 노드에게 데이터 응답을 요청하는 역할을 한다.",
  },
  {
    question: "FlexRay 통신에서 'Cycle(사이클)' 내에서 Static Segment(정적 세그먼트)가 Dynamic Segment(동적 세그먼트)보다 먼저 배치되는 주된 이유는?",
    options: ["동적 세그먼트의 유연성 확보", "시간 보장형 메시지의 실시간성 확보", "메시지 우선순위 중재", "전력 소비 최소화"],
    answer: 1,
    explain: "Static Segment는 시간 보장이 필수적인 핵심 메시지를 전송하므로, Cycle의 시작 부분에 배치하여 실시간성을 최우선으로 확보한다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Error Active' 상태일 때, 버스에 오류를 알리기 위해 전송하는 Active Error Flag의 비트 길이는?",
    options: ["6 Dominant 비트", "6 Recessive 비트", "8 Recessive 비트", "8 Dominant 비트"],
    answer: 0,
    explain: "Error Active 상태의 ECU는 6개의 Dominant 비트를 전송하여 모든 ECU가 오류를 인지하고 현재 메시지 전송을 강제로 중단하도록 한다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, 'ECU 통신 세션의 변경'을 요청하는 서비스 ID는?",
    options: ["$0x10", "$0x14", "$0x22", "$0x27"],
    answer: 0,
    explain: "서비스 ID $0x10은 'DiagnosticSessionControl'로, 기본 세션에서 확장 또는 프로그래밍 세션으로 전환하는 데 사용된다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-H와 CAN-L의 차동 신호(Differential Signal)를 사용하는 주된 이유는?",
    options: ["통신 속도 증가", "전력 소비 감소", "외부 노이즈에 대한 강한 내성 확보", "메시지 우선순위 중재"],
    answer: 2,
    explain: "차동 신호는 외부 노이즈가 두 라인에 동시에 영향을 주더라도 차동 전압에는 변화가 없어 노이즈 내성이 높다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 응답하는 Data Field의 최대 길이는 몇 바이트인가?",
    options: ["2 바이트", "4 바이트", "8 바이트", "64 바이트"],
    answer: 2,
    explain: "LIN 데이터 필드는 1바이트부터 8바이트까지 전송할 수 있으며, 일반적인 CAN과 동일하게 최대 8바이트이다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment'에서 메시지 전송 시 충돌을 방지하기 위해 사용하는 기법은?",
    options: ["메시지 ID 기반의 중재", "Master-slave 제어", "시간 기반의 Mini-slot을 이용한 중재", "토큰 패싱"],
    answer: 2,
    explain: "Dynamic Segment는 유연성을 위해 Mini-slot을 사용하며, 노드가 전송을 원할 경우 Mini-slot을 선점하여 메시지 충돌을 방지한다.",
  },
  {
    question: "CAN 통신에서 Bit Stuffing 규칙 위반(연속 6개 동일 레벨 비트 발생)이 감지되었을 때 발생하는 오류 유형은?",
    options: ["Bit Error", "Stuff Error", "Form Error", "CRC Error"],
    answer: 1,
    explain: "Stuff Error(스터프 오류)는 Bit Stuffing 규칙에 따라 삽입되어야 할 비트가 없거나, 연속 5개 이상의 동일 비트 레벨이 발생하는 경우에 검출된다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, ECU의 보안 접근(Security Access)을 위해 'Seed' 값을 요청하는 서비스 ID는?",
    options: ["$0x10", "$0x14", "$0x27", "$0x2F"],
    answer: 2,
    explain: "서비스 ID $0x27은 'SecurityAccess'로, ECU의 잠금 해제를 위한 Seed-Key 교환 절차의 첫 단계인 Seed를 요청한다.",
  },
  {
    question: "LIN 통신에서 Sync Break 필드가 헤더의 가장 앞에 위치하는 주된 목적은?",
    options: ["데이터 오류 검출", "슬레이브 노드의 물리적인 동기화", "메시지 우선순위 결정", "마스터 노드의 데이터 전송"],
    answer: 1,
    explain: "Sync Break는 일반적인 통신 비트 폭보다 긴 길이로, 슬레이브 노드가 통신 시작을 인지하고 비트 타이밍을 마스터와 동기화하는 데 사용된다.",
  },
  {
    question: "CAN 통신에서 ECU의 트랜시버가 CAN-L 라인에만 지속적인 단락(Short to VCC)을 발생시켰을 때, 버스의 차동 전압 파형은?",
    options: ["파형의 진폭이 감소하고 Dominant 상태로 고정", "파형의 진폭이 감소하고 Recessive 상태로 고정", "파형의 주파수만 감소", "파형이 Recessive 상태로 고정"],
    answer: 1,
    explain: "CAN-L이 VCC에 단락되면 CAN-H와의 전압 차이가 줄어들어 Recessive 상태를 유지하려 하여 통신 불능 상태가 된다.",
  }  
];

export const industry010805 = [
{
    question: "CAN 통신에서 표준 프레임(Standard Frame)과 확장 프레임(Extended Frame)을 구분하는 필드는 무엇인가?",
    options: ["Data Length Code (DLC)", "RTR (Remote Transmission Request) Bit", "IDE (Identifier Extension) Bit", "CRC Field"],
    answer: 2,
    explain: "IDE(Identifier Extension Bit)는 표준 프레임에서는 Recessive로, 확장 프레임에서는 Dominant로 전송되어 프레임 유형을 구분한다.",
  },
  {
    question: "FlexRay 통신에서 높은 신뢰성을 위해 두 개의 채널(Channel A, Channel B)을 이용하여 통신할 때, 채널 간의 주된 차이점은 무엇인가?",
    options: ["채널 A는 Static, 채널 B는 Dynamic 세그먼트만 전송한다.", "채널 A는 CAN, 채널 B는 LIN 프로토콜을 사용한다.", "두 채널 모두 동일한 데이터와 구조를 가지며 이중화에 사용된다.", "채널 A는 전원선, 채널 B는 접지선 역할을 한다."],
    answer: 2,
    explain: "FlexRay 이중화(Redundancy)는 두 채널이 동일한 통신 구조와 데이터를 가지며, 오류 발생 시 서로를 백업하여 신뢰성을 높인다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 슬레이브 노드에 데이터 전송을 요청하는 '폴링(Polling)' 역할을 하는 필드는?",
    options: ["Sync Break", "Sync Field", "Identifier Field (식별자)", "Data Field"],
    answer: 2,
    explain: "마스터가 전송하는 ID(식별자)는 버스상의 슬레이브 노드 중 해당 ID의 데이터가 필요한 노드를 지정하여 응답(데이터 전송)을 요청한다.",
  },
  {
    question: "CAN 트랜시버(Transceiver)에서 TXD(Transmit Data) 입력 라인이 접지(Ground)에 단락되었을 때, 버스 상태에 미치는 영향은?",
    options: ["버스 전체가 Recessive 상태로 고정된다.", "트랜시버가 지속적으로 Dominant 비트만 출력하여 통신 불능 상태가 된다.", "통신 속도가 절반으로 줄어든다.", "CAN 통신이 정상적으로 작동한다."],
    answer: 1,
    explain: "트랜시버는 TXD 입력이 Dominant(낮은 전압)일 때 Dominant 신호를 버스에 출력하며, 접지 단락은 지속적인 Dominant 입력을 유발한다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, ECU에 저장된 영구적인 고장 코드(DTC)를 지우도록 요청하는 서비스 ID는?",
    options: ["$0x03", "$0x04", "$0x14", "$0x19"],
    answer: 1,
    explain: "서비스 ID $0x04는 'Clear Diagnostic Information'으로, ECU에 저장된 고장 코드 및 관련 데이터를 삭제하도록 요청한다.",
  },
  {
    question: "CAN 통신에서 'Remote Frame(원격 프레임)'의 주된 목적은 무엇인가?",
    options: ["긴급 데이터 전송", "오류 메시지 전송", "다른 ECU에게 특정 데이터 전송 요청", "메시지 우선순위 설정"],
    answer: 2,
    explain: "Remote Frame은 데이터 필드 없이 특정 메시지 ID를 전송하여, 해당 데이터를 가진 ECU에게 데이터 프레임 전송을 요청한다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 슬레이브 노드의 클럭 동기화에 사용되는 'Sync Field'는 몇 비트로 구성되는가?",
    options: ["8 비트 (0x55)", "10 비트 (0xAA)", "16 비트 (0xFF)", "32 비트 (0x00)"],
    answer: 0,
    explain: "Sync Field는 1바이트(8비트)로, 비트 타이밍 동기화를 위해 패턴 0x55 (01010101)를 사용한다.",
  },
  {
    question: "FlexRay 통신에서 'Cycle(사이클)'이 갖는 가장 중요한 의미는?",
    options: ["단일 메시지 전송 시간", "통신 속도", "Static Segment와 Dynamic Segment를 모두 포함하는 전체 통신 주기", "오류 발생 시 재전송 횟수"],
    answer: 2,
    explain: "FlexRay 사이클은 정적 세그먼트와 동적 세그먼트, 그리고 가드 시간 등을 포함하는 전체 반복 통신 주기를 의미하며, 시간 동기화의 기본 단위이다.",
  },
  {
    question: "CAN 통신에서 Bit Stuffing 규칙 위반(연속 6개 동일 레벨 비트 발생)이 감지되었을 때 발생하는 오류 유형은?",
    options: ["Bit Error", "Stuff Error", "Form Error", "CRC Error"],
    answer: 1,
    explain: "Stuff Error(스터프 오류)는 Bit Stuffing 규칙에 따라 삽입되어야 할 비트가 없거나, 연속 5개 이상의 동일 비트 레벨이 발생하는 경우에 검출된다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, ECU의 보안 접근(Security Access)을 위해 'Seed' 값을 요청하는 서비스 ID는?",
    options: ["$0x10", "$0x14", "$0x27", "$0x2F"],
    answer: 2,
    explain: "서비스 ID $0x27은 'SecurityAccess'로, ECU의 잠금 해제를 위한 Seed-Key 교환 절차의 첫 단계인 Seed를 요청한다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-H와 CAN-L 두 신호선이 단락(Short)되었을 때, 버스의 차동 전압 파형은?",
    options: ["파형의 진폭이 2배로 증가", "파형의 진폭이 증가하고 Dominant 상태로 고정", "파형의 주파수만 감소", "파형이 Recessive 상태로 고정되어 차동 전압 0V에 가까워짐"],
    answer: 3,
    explain: "두 라인이 단락되면 차동 전압이 0V에 가까워져 Recessive 상태와 유사하게 되며, 통신 신호를 구별할 수 없어 통신 불능 상태가 된다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 슬립 모드에서 벗어나기 위해 수신해야 하는 Wakeup Signal의 특징은?",
    options: ["Sync Break 신호와 동일하다.", "일반 비트보다 짧은 Dominant 펄스이다.", "일반 비트보다 긴 Dominant 펄스이다.", "Recessive 비트만 연속된다."],
    answer: 2,
    explain: "Wakeup Signal은 일반적인 데이터 비트 폭보다 긴 Dominant 펄스 형태로 전송되어, 슬립 상태의 노드가 통신 시작을 감지하도록 한다.",
  },
  {
    question: "FlexRay 통신에서 'Static Segment'의 타임 슬롯이 결정론적(Deterministic) 특성을 갖는 주된 이유는?",
    options: ["버스 전압이 항상 5V로 유지되기 때문에", "메시지 ID가 낮은 것이 우선순위를 갖기 때문에", "타임 슬롯이 시스템 설계 시 미리 할당되고 고정되기 때문에", "메시지 길이가 유동적이기 때문에"],
    answer: 2,
    explain: "결정론적 통신은 메시지 전송 시간이 예측 가능하다는 의미이며, Static Segment는 시간 슬롯이 고정되어 이 특성을 보장한다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Error Passive' 상태일 때, 해당 ECU가 전송하는 오류 플래그(Error Flag)의 특징은?",
    options: ["6개의 Dominant 비트", "8개의 Dominant 비트", "6개의 Recessive 비트", "8개의 Recessive 비트"],
    answer: 3,
    explain: "Error Passive 상태의 ECU는 8개의 Recessive 비트를 전송하여, 다른 ECU의 통신에 미치는 영향을 최소화한다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, '특정 진단 기능의 제어'를 요청하는 서비스 ID는?",
    options: ["$0x14", "$0x22", "$0x27", "$0x2F"],
    answer: 3,
    explain: "서비스 ID $0x2F는 'InputOutputControlByIdentifier'로, 특정 부품의 작동을 활성화/비활성화하거나 값을 변경하는 제어 기능을 요청한다.",
  },
  {
    question: "고속 CAN 통신에서 버스 종단 저항(Termination Resistor)이 규정 값(60Ω)보다 현저히 높은 상태(예: 120Ω 이상)일 때, 나타나는 주된 통신 문제는?",
    options: ["버스 전체가 Dominant 상태로 고정된다.", "통신 속도가 2배로 증가한다.", "버스에서 신호 반사가 발생하여 파형 왜곡이 심해진다.", "ECU의 전력 소비가 증가한다."],
    answer: 2,
    explain: "종단 저항이 높으면 임피던스 정합이 불량해져 신호가 통신선 끝에서 반사되어 원래 신호와 겹쳐 파형 왜곡(링잉 현상)을 일으킨다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드의 클럭 동기화에 사용되는 'Sync Field'를 전송하는 주체는?",
    options: ["슬레이브 노드", "CAN 게이트웨이", "마스터 노드", "트랜시버"],
    answer: 2,
    explain: "Sync Field는 마스터 노드가 Sync Break 다음에 전송하여 슬레이브 노드들의 내부 클럭을 마스터와 동기화하는 데 사용된다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment'의 유연한 타임 슬롯 할당 방식에서 메시지 충돌을 방지하기 위해 사용하는 기법은?",
    options: ["메시지 ID 기반의 중재", "Master-slave 제어", "시간 기반의 Mini-slot을 이용한 중재", "토큰 패싱"],
    answer: 2,
    explain: "Dynamic Segment는 유연성을 위해 Mini-slot을 사용하며, 노드가 전송을 원할 경우 Mini-slot을 선점하여 메시지 충돌을 방지한다.",
  },
  {
    question: "CAN 통신에서 Recessive 비트 상태 시, CAN-H와 CAN-L의 공통 모드 전압(Common Mode Voltage)은 일반적으로 몇 V 인가?",
    options: ["0V", "1.5V", "2.5V", "3.5V"],
    answer: 2,
    explain: "Recessive 상태는 버스 휴지 상태로, CAN-H와 CAN-L 모두 공통 모드 전압인 약 2.5V를 유지하여 차동 전압이 0V에 가깝다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, 'ECU의 식별 정보(예: 부품 번호, 소프트웨어 버전)'를 요청하는 서비스 ID는?",
    options: ["$0x10", "$0x14", "$0x22", "$0x27"],
    answer: 2,
    explain: "서비스 ID $0x22는 'ReadDataByIdentifier'로, ECU의 메모리나 식별 정보(예: VIN, 부품 번호)를 요청한다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-H와 CAN-L의 차동 신호(Differential Signal)를 사용하는 주된 이유는?",
    options: ["통신 속도 증가", "전력 소비 감소", "외부 노이즈에 대한 강한 내성 확보", "메시지 우선순위 중재"],
    answer: 2,
    explain: "차동 신호는 외부 노이즈가 두 라인에 동시에 영향을 주더라도 차동 전압에는 변화가 없어 노이즈 내성이 높다.",
  },
  {
    question: "LIN 통신 프레임에서 슬레이브 노드의 데이터 전송이 지연되거나 누락되는 주된 오류 유형은?",
    options: ["Form Error", "Stuff Error", "Frame Error (응답 지연)", "CRC Error"],
    answer: 2,
    explain: "마스터가 헤더를 전송했음에도 불구하고, 슬레이브 노드의 응답(Response)이 지정된 시간 내에 오지 않거나 누락될 때 Frame Error로 간주된다.",
  },
  {
    question: "FlexRay 통신에서 'Cycle' 내에서 Static Segment(정적 세그먼트)가 Dynamic Segment(동적 세그먼트)보다 먼저 배치되는 주된 이유는?",
    options: ["동적 세그먼트의 유연성 확보", "시간 보장형 메시지의 실시간성 확보", "메시지 우선순위 중재", "전력 소비 최소화"],
    answer: 1,
    explain: "Static Segment는 시간 보장이 필수적인 핵심 메시지를 전송하므로, Cycle의 시작 부분에 배치하여 실시간성을 최우선으로 확보한다.",
  },
  {
    question: "CAN 통신에서 ECU가 'Bus-Off' 상태에서 'Bus-On' 상태로 복귀하기 위해 만족해야 하는 가장 중요한 조건은?",
    options: ["전송 오류 카운터를 0으로 초기화", "메시지 우선순위를 낮춘다.", "Recessive 비트를 128회 연속 감지", "CAN 버스를 5초간 모니터링"],
    answer: 2,
    explain: "Bus-Off 상태의 ECU는 버스가 128회 연속 Recessive 비트(버스 휴지 상태)임을 감지해야만 다시 Bus-On(Error Passive) 상태로 복귀할 수 있다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, '요청 시점의 현재 데이터'를 확인하기 위해 사용하는 서비스 ID는?",
    options: ["$0x01", "$0x02", "$0x03", "$0x04"],
    answer: 0,
    explain: "서비스 ID $0x01은 '요청 시점의 현재 진단 데이터'를 의미하며, PID를 통해 특정 센서 값 등을 요청한다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-L 라인이 단선(Open)되어 전원(VCC, 5V)에 단락(Short to VCC)되었을 때, 버스 상태에 미치는 영향은?",
    options: ["버스 전체가 Recessive 상태로 고정되어 통신 불능 상태가 된다.", "CAN-H 라인이 통신을 이어받아 정상 통신한다.", "버스 전체가 Dominant 상태로 고정되어 통신 불능 상태가 된다.", "통신 속도가 절반으로 줄어든다."],
    answer: 2,
    explain: "CAN-L이 VCC에 단락되면 CAN-L의 전위가 높아지고, CAN-H와의 차동 전압이 Dominant 상태를 유지하게 되어 버스가 Dominant 고정으로 통신 불능이 된다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 Wakeup Signal을 수신한 후, 통신에 참여하기 위해 수행하는 조치는?",
    options: ["메시지 ID를 마스터에게 전송", "버스 전압을 5V로 고정", "내부 클럭을 마스터와 동기화", "Bus-Off 상태로 진입"],
    answer: 2,
    explain: "Wakeup Signal 수신 후, 슬레이브는 슬립 모드에서 벗어나 통신에 참여하며, Sync Field를 통해 클럭 동기화를 재수행한다.",
  },
  {
    question: "FlexRay 통신에서 'Static Segment'에서 메시지 전송 시 충돌이 발생하지 않는 주된 이유는?",
    options: ["Dominant/Recessive 중재 사용", "Single-wire 통신", "메시지 ID 우선순위 사용", "미리 할당된 Time Slot 사용"],
    answer: 3,
    explain: "Static Segment에서는 각 노드가 지정된 Time Slot에만 전송을 허용하므로 메시지 간의 충돌 자체가 발생하지 않는다.",
  },
  {
    question: "CAN 통신에서 ECU의 트랜시버가 RXD(Receive Data) 출력 라인에 단선(Open) 고장이 발생했을 때, 해당 ECU의 메시지 수신 상태는?",
    options: ["메시지 전송만 불가능하다.", "메시지 수신은 가능하나, CAN 컨트롤러로 데이터 전달이 안 된다.", "송수신 모두 불가능하다.", "CAN 통신이 정상적으로 작동한다."],
    answer: 1,
    explain: "트랜시버는 버스 신호를 RXD를 통해 컨트롤러에 전달하므로, RXD 단선 시 버스 수신은 가능하지만 컨트롤러는 데이터를 받을 수 없다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, 'ECU 통신 세션의 변경'을 요청하는 서비스 ID는?",
    options: ["$0x10", "$0x14", "$0x22", "$0x27"],
    answer: 0,
    explain: "서비스 ID $0x10은 'DiagnosticSessionControl'로, 기본 세션에서 확장 또는 프로그래밍 세션으로 전환하는 데 사용된다.",
  },
  {
    question: "고속 CAN 통신에서 버스 종단 저항(Termination Resistor)이 규정 값(60Ω)보다 현저히 낮은 상태(예: 30Ω 이하)일 때, 나타나는 주된 통신 문제는?",
    options: ["버스에 흐르는 전류가 과도하게 증가하여 트랜시버에 부하 발생", "신호 반사가 발생하여 파형 왜곡이 심해진다.", "버스 전체가 Recessive 상태로 고정된다.", "통신 속도가 감소한다."],
    answer: 0,
    explain: "저항이 낮아지면 버스의 총 전류가 증가하여 트랜시버에 과도한 부하가 걸리고 신호 전압 레벨이 낮아져 통신이 어려워진다.",
  },
  {
    question: "LIN 통신에서 마스터 노드가 슬레이브 노드에게 데이터를 요청하는 필드가 포함된 부분은?",
    options: ["Response (응답)", "Checksum", "Header (헤더)", "Data Field"],
    answer: 2,
    explain: "LIN 헤더는 Sync Break, Sync Field, ID Field로 구성되며, ID Field가 슬레이브 노드에게 데이터 응답을 요청하는 역할을 한다.",
  },
  {
    question: "FlexRay 통신에서 'Startup Frame(시작 프레임)'을 전송하는 주된 목적은?",
    options: ["비주기적인 이벤트 데이터 전송", "통신 속도 조절", "버스상의 모든 노드의 동기화(Sync) 및 클럭 동기", "메시지 우선순위 중재"],
    answer: 2,
    explain: "Startup Frame은 FlexRay 통신 사이클의 시작을 알리고, 버스상의 모든 노드의 시간 동기화를 확립하는 데 사용된다.",
  },
  {
    question: "CAN 통신에서 Dominant 비트 상태 시, CAN-H와 CAN-L의 공통 모드 전압(Common Mode Voltage)은 일반적으로 몇 V 인가?",
    options: ["0V", "1.5V", "2.5V", "3.5V"],
    answer: 2,
    explain: "Dominant 상태에서도 공통 모드 전압은 약 2.5V를 유지하며, CAN-H는 3.5V, CAN-L은 1.5V로 차동 전압이 2V가 된다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, '저장된 고장 코드(DTC)'를 확인하기 위해 사용하는 서비스 ID는?",
    options: ["$0x01", "$0x02", "$0x03", "$0x04"],
    answer: 2,
    explain: "서비스 ID $0x03은 '저장된 고장 코드(Diagnostic Trouble Code, DTC)'를 요청하는 서비스이다.",
  },
  {
    question: "고속 CAN 통신에서 CAN-H 라인이 단선(Open)되어 접지(Ground)에 단락(Short to Ground)되었을 때, 버스 상태에 미치는 영향은?",
    options: ["통신 속도가 절반으로 줄어든다.", "CAN-L 라인이 통신을 이어받아 정상 통신한다.", "버스 전체가 Dominant 상태로 고정되어 통신 불능 상태가 된다.", "버스 전체가 Recessive 상태로 고정되어 통신 불능 상태가 된다."],
    answer: 2,
    explain: "CAN-H가 접지 단락되면 CAN-H의 전위가 낮아지고, CAN-L과의 차동 전압이 Dominant 상태를 유지하게 되어 버스가 Dominant 고정으로 통신 불능이 된다.",
  },
  {
    question: "LIN 통신에서 슬레이브 노드가 응답하는 Data Field의 최대 길이는 몇 바이트인가?",
    options: ["2 바이트", "4 바이트", "8 바이트", "64 바이트"],
    answer: 2,
    explain: "LIN 데이터 필드는 1바이트부터 8바이트까지 전송할 수 있으며, 일반적인 CAN과 동일하게 최대 8바이트이다.",
  },
  {
    question: "FlexRay 통신에서 'Dynamic Segment'의 타임 슬롯은 누가 소유하며 데이터를 전송하는가?",
    options: ["가장 높은 ID를 가진 ECU", "가장 낮은 ID를 가진 ECU", "통신 매트릭스에 지정된 단 하나의 ECU", "메시지 전송이 필요한 노드들이 선점 방식으로 사용"],
    answer: 3,
    explain: "Dynamic Segment는 유연성을 위해 Mini-slot을 사용하며, 메시지 전송이 필요한 노드가 선점 방식으로 타임 슬롯을 사용한다.",
  },
  {
    question: "CAN 통신에서 메시지 ID가 낮은 ECU가 메시지 충돌 시 우선권을 갖는 통신 방식을 무엇이라고 하는가?",
    options: ["Time-Triggered", "Master-Slave", "Token Passing", "Non-Destructive Arbitration (비파괴적 중재)"],
    answer: 3,
    explain: "CAN은 Dominant/Recessive 논리를 이용한 비파괴적 중재를 통해 ID가 낮은(우선순위 높은) 메시지가 버스 제어권을 획득한다.",
  },
  {
    question: "OBD-II 기반 진단 프로토콜(UDS)에서, 'ECU의 메모리(DTC 또는 데이터)를 읽는' 범용 서비스 ID는?",
    options: ["$0x10", "$0x14", "$0x22", "$0x27"],
    answer: 2,
    explain: "서비스 ID $0x22는 'ReadDataByIdentifier'로, 특정 ID가 지정하는 ECU의 저장 데이터를 읽는 데 사용된다.",
  }
    
];